Repository NVIDIA/cloudai, pull requests merged in 2024-08, with the labels that each got.

#146 Add job_status_check flag to disable checks for specific tests
  src/cloudai/_core/base_runner.py
  src/cloudai/_core/test_scenario.py
  src/cloudai/_core/test_scenario_parser.py
Labels: bug, enhancement

#164 Defer docker image URL accessibility check to srun when not caching locally
  src/cloudai/util/docker_image_cache_manager.py
Labels: bug

#141 Hierarchical Test template for support Grok/GPT via PAXML
  src/cloudai/_core/test_parser.py
  src/cloudai/schema/test_template/jax_toolbox/slurm_command_gen_strategy.py
  tests/test_slurm_command_gen_strategy.py
Labels: enhancement

#170 Add Pre-test for long LLMs run on Coreweave
  src/cloudai/schema/test_template/jax_toolbox/slurm_command_gen_strategy.py
  src/cloudai/systems/slurm/strategy/slurm_command_gen_strategy.py
  tests/test_slurm_command_gen_strategy.py
Labels: Oct24

#176 Redefine Job, Runner, and System Responsibilities; Refactor Classes
  src/cloudai/_core/base_job.py
  src/cloudai/_core/base_runner.py
  src/cloudai/_core/system.py
  src/cloudai/_core/test_scenario_parser.py
  src/cloudai/runner/slurm/slurm_job.py
  src/cloudai/runner/slurm/slurm_runner.py
  src/cloudai/runner/standalone/standalone_job.py
  src/cloudai/runner/standalone/standalone_runner.py
  src/cloudai/systems/slurm/slurm_system.py
  src/cloudai/systems/standalone_system.py
  tests/test_base_runner.py
  tests/test_standalone_system.py
Labels: enhancement, Oct24

#179 Move Common Variables to System class and TestTemplateStrategy
  src/cloudai/_core/system.py
  src/cloudai/_core/test_template_strategy.py
  src/cloudai/systems/slurm/slurm_system.py
  src/cloudai/systems/slurm/strategy/slurm_command_gen_strategy.py
  src/cloudai/systems/standalone_system.py
Labels: enhancement, Oct24
