Repository NVIDIA/cloudai, pull requests merged in 2024-10, with the labels that each got.

#221 Use absolute paths in NeMo launcher
  src/cloudai/schema/test_template/nemo_launcher/slurm_command_gen_strategy.py
Labels: bug, Oct24

#223 Unset argument in NeMo launcher when its value is ~
  src/cloudai/schema/test_template/nemo_launcher/slurm_command_gen_strategy.py
  tests/test_slurm_command_gen_strategy.py
Labels: bug, enhancement, Oct24

#222 Rename NeMo-related TOML configurations to reflect the exact model
  conf/common/test/gpt3_40b.toml
  conf/common/test/llama2_70b.toml
Labels: enhancement, Oct24

#224 Use mock data by default in NeMo launcher
  src/cloudai/schema/test_template/nemo_launcher/slurm_command_gen_strategy.py
  src/cloudai/test_definitions/nemo_launcher.py
  tests/test_slurm_command_gen_strategy.py
Labels: bug, enhancement, Oct24

#219 Generate Bash script during Nemo Launcher
  src/cloudai/schema/test_template/nemo_launcher/slurm_command_gen_strategy.py
  src/cloudai/test_definitions/nemo_launcher.py
  tests/test_slurm_command_gen_strategy.py
Labels: enhancement, Oct24

#226 Remove unnecessary indirections
  src/cloudai/_core/base_runner.py
  src/cloudai/_core/test.py
  src/cloudai/runner/slurm/slurm_runner.py
  src/cloudai/runner/standalone/standalone_runner.py
  tests/test_job_submission_error.py
Labels: enhancement, Oct24

#227 Remove Installer class to reduce code indirection
  src/cloudai/__init__.py
  src/cloudai/__main__.py
  src/cloudai/installer/installer.py
Labels: enhancement, Oct24

#229 Refactor SlurmCommandGenStrategy
  src/cloudai/schema/test_template/chakra_replay/slurm_command_gen_strategy.py
  src/cloudai/schema/test_template/jax_toolbox/slurm_command_gen_strategy.py
  src/cloudai/schema/test_template/nccl_test/slurm_command_gen_strategy.py
  src/cloudai/schema/test_template/sleep/slurm_command_gen_strategy.py
  src/cloudai/schema/test_template/ucc_test/slurm_command_gen_strategy.py
  src/cloudai/systems/slurm/strategy/slurm_command_gen_strategy.py
  tests/test_slurm_command_gen_strategy.py
Labels: enhancement

#230 Use venv for nemo launcher
  src/cloudai/schema/test_template/nemo_launcher/slurm_command_gen_strategy.py
  src/cloudai/schema/test_template/nemo_launcher/slurm_install_strategy.py
  tests/test_slurm_install_strategy.py
Labels: enhancement

#228 Pass TestRun to gen_exec_command and gen_json
  src/cloudai/_core/base_job.py
  src/cloudai/_core/command_gen_strategy.py
  src/cloudai/_core/json_gen_strategy.py
  src/cloudai/_core/test.py
  src/cloudai/_core/test_scenario.py
  src/cloudai/_core/test_template.py
  src/cloudai/runner/kubernetes/kubernetes_job.py
  src/cloudai/runner/kubernetes/kubernetes_runner.py
  src/cloudai/runner/slurm/slurm_job.py
  src/cloudai/runner/slurm/slurm_runner.py
  src/cloudai/runner/standalone/standalone_job.py
  src/cloudai/runner/standalone/standalone_runner.py
  src/cloudai/schema/test_template/chakra_replay/slurm_command_gen_strategy.py
  src/cloudai/schema/test_template/jax_toolbox/slurm_command_gen_strategy.py
  src/cloudai/schema/test_template/nccl_test/kubernetes_json_gen_strategy.py
  src/cloudai/schema/test_template/nccl_test/slurm_command_gen_strategy.py
  src/cloudai/schema/test_template/nemo_launcher/slurm_command_gen_strategy.py
  src/cloudai/schema/test_template/sleep/kubernetes_json_gen_strategy.py
  src/cloudai/schema/test_template/sleep/slurm_command_gen_strategy.py
  src/cloudai/schema/test_template/sleep/standalone_command_gen_strategy.py
  src/cloudai/schema/test_template/ucc_test/slurm_command_gen_strategy.py
  tests/test_slurm_command_gen_strategy.py
  tests/test_standalone_system.py
Labels: enhancement

#231 Bug fix for incorrect py_bin in NeMoLauncher
  src/cloudai/schema/test_template/nemo_launcher/slurm_command_gen_strategy.py
Labels: bug, Oct24

#205 Pydantic for Test Scenario
  .github/workflows/ci.yml
  README.md
  USER_GUIDE.md
  conf/common/test_scenario/chakra_replay.toml
  conf/common/test_scenario/nccl_test.toml
  conf/common/test_scenario/nemo_launcher.toml
  conf/common/test_scenario/nemo_launcher_with_noise.toml
  conf/common/test_scenario/sleep.toml
  conf/common/test_scenario/ucc_test.toml
  conf/release/spcx/l40s/test_scenario/l40s_bc_nccl_test.toml
  src/cloudai/__init__.py
  src/cloudai/__main__.py
  src/cloudai/_core/base_job.py
  src/cloudai/_core/base_runner.py
  src/cloudai/_core/exceptions.py
  src/cloudai/_core/grader.py
  src/cloudai/_core/test.py
  src/cloudai/_core/test_scenario.py
  src/cloudai/_core/test_scenario_parser.py
  src/cloudai/parser.py
  src/cloudai/report_generator/report_generator.py
  src/cloudai/runner/kubernetes/kubernetes_runner.py
  src/cloudai/runner/slurm/slurm_runner.py
  src/cloudai/runner/standalone/standalone_runner.py
  src/cloudai/schema/test_template/nccl_test/kubernetes_json_gen_strategy.py
  src/cloudai/schema/test_template/sleep/kubernetes_json_gen_strategy.py
  tests/test_job_submission_error.py
  tests/test_slurm_command_gen_strategy.py
  tests/test_test_scenario.py
  tests/test_toml_files.py
Labels: Oct24, feature

#234 Update Sleep to ensure implementation consistency
  src/cloudai/schema/test_template/sleep/slurm_command_gen_strategy.py
Labels: enhancement, Oct24

#235 Update USER_GUIDE.md and README.md
  README.md
  USER_GUIDE.md
Labels: documentation, Oct24

#233 Remove duplicated _format_env_vars calls
  src/cloudai/schema/test_template/chakra_replay/slurm_command_gen_strategy.py
  src/cloudai/schema/test_template/jax_toolbox/slurm_command_gen_strategy.py
  src/cloudai/schema/test_template/nccl_test/slurm_command_gen_strategy.py
  src/cloudai/schema/test_template/sleep/slurm_command_gen_strategy.py
  src/cloudai/schema/test_template/ucc_test/slurm_command_gen_strategy.py
  src/cloudai/systems/slurm/strategy/slurm_command_gen_strategy.py
  tests/test_slurm_command_gen_strategy.py
Labels: enhancement, Oct24

#238 Remove unnecessary arg from generate_test_command
  src/cloudai/schema/test_template/chakra_replay/slurm_command_gen_strategy.py
  src/cloudai/schema/test_template/nccl_test/slurm_command_gen_strategy.py
  src/cloudai/schema/test_template/sleep/slurm_command_gen_strategy.py
  src/cloudai/schema/test_template/ucc_test/slurm_command_gen_strategy.py
  src/cloudai/systems/slurm/strategy/slurm_command_gen_strategy.py
  tests/test_slurm_command_gen_strategy.py
Labels: enhancement, Oct24

#239 Expect SlurmSystem in respective cmd_gen and installer classes
  src/cloudai/installer/slurm_installer.py
  src/cloudai/schema/test_template/jax_toolbox/slurm_command_gen_strategy.py
  src/cloudai/schema/test_template/nemo_launcher/slurm_command_gen_strategy.py
  src/cloudai/schema/test_template/nemo_launcher/slurm_install_strategy.py
  src/cloudai/systems/slurm/strategy/slurm_command_gen_strategy.py
  src/cloudai/systems/slurm/strategy/slurm_install_strategy.py
  tests/test_slurm_command_gen_strategy.py
  tests/test_slurm_install_strategy.py
Labels: enhancement, Oct24

#240 Move more fields from Test to TestRun
  src/cloudai/_core/grader.py
  src/cloudai/_core/test.py
  src/cloudai/_core/test_scenario.py
  src/cloudai/_core/test_scenario_parser.py
  src/cloudai/report_generator/report_generator.py
  tests/test_test_scenario.py
Labels: enhancement, Oct24

#241 Make TestDefinition a part of Test
  src/cloudai/_core/test.py
  src/cloudai/_core/test_parser.py
  src/cloudai/_core/test_scenario_parser.py
  src/cloudai/_core/test_template.py
  src/cloudai/schema/test_template/nemo_launcher/slurm_command_gen_strategy.py
  tests/test_job_submission_error.py
  tests/test_slurm_command_gen_strategy.py
  tests/test_test_scenario.py
Labels: enhancement, Oct24

#246 Minor refactoring on SlurmCommandGenStrategy
  src/cloudai/schema/test_template/jax_toolbox/slurm_command_gen_strategy.py
  src/cloudai/systems/slurm/strategy/slurm_command_gen_strategy.py
Labels: enhancement, Oct24

#245 Break down test_slurm_command_gen_strategy into smaller tests
  tests/slurm_command_gen_strategy/conftest.py
  tests/slurm_command_gen_strategy/test_common.py
  tests/slurm_command_gen_strategy/test_nccl.py
  tests/slurm_command_gen_strategy/test_nemo_launcher.py
  tests/test_slurm_command_gen_strategy.py
Labels: enhancement, Oct24

#242 Resolve K8s Comments (Part 1)
  conf/common/system/kubernetes_cluster.toml
  src/cloudai/runner/kubernetes/kubernetes_job.py
  src/cloudai/runner/kubernetes/kubernetes_runner.py
  src/cloudai/schema/test_template/sleep/kubernetes_json_gen_strategy.py
  src/cloudai/systems/kubernetes/kubernetes_system.py
  src/cloudai/test_definitions/sleep.py
  tests/test_kubernetes_system.py
Labels: enhancement, Oct24

#248 Fix race condition during docker images caching
  src/cloudai/__main__.py
  tests/test_acceptance.py
Labels: bug, Oct24

#244 Fix bug in violating Kubernetes naming rules
  src/cloudai/_core/json_gen_strategy.py
  src/cloudai/schema/test_template/nccl_test/kubernetes_json_gen_strategy.py
Labels: bug, Oct24

#247 Add unit tests for SlurmCommandGenStrategy
  tests/slurm_command_gen_strategy/test_chakra_replay.py
  tests/slurm_command_gen_strategy/test_nccl.py
  tests/slurm_command_gen_strategy/test_sleep.py
  tests/slurm_command_gen_strategy/test_ucc.py
Labels: enhancement, Oct24

#251 Fix missing 'output_path' in cmd_args
  src/cloudai/schema/test_template/jax_toolbox/slurm_command_gen_strategy.py
Labels: bug, Oct24

#250 Remove assigning null when the value is null (NeMo launcher)
  src/cloudai/schema/test_template/nemo_launcher/slurm_command_gen_strategy.py
  src/cloudai/test_definitions/nemo_launcher.py
  tests/slurm_command_gen_strategy/test_nemo_launcher.py
Labels: bug, Oct24

#252 Refactor NeMoLauncherSlurmCommandGenStrategy unit tests
  tests/slurm_command_gen_strategy/test_nemo_launcher.py
Labels: enhancement, Oct24

#194 Use subcommands instead of `--mode <value>`
  .github/workflows/ci.yml
  README.md
  USER_GUIDE.md
  pyproject.toml
  src/cloudai/__main__.py
  src/cloudai/cli/__init__.py
  src/cloudai/cli/cli.py
  src/cloudai/cli/handlers.py
  tests/test_acceptance.py
  tests/test_cli.py
Labels: feature

#254 Refactor JaxToolboxSlurmCommandGenStrategy
  src/cloudai/schema/test_template/jax_toolbox/slurm_command_gen_strategy.py
Labels: enhancement, Oct24

#257 Move JaxToolbox-related test definitions to CloudAI
  src/cloudai/__init__.py
  src/cloudai/test_definitions/__init__.py
  src/cloudai/test_definitions/gpt.py
  src/cloudai/test_definitions/grok.py
  src/cloudai/test_definitions/jax_toolbox.py
  src/cloudai/test_definitions/nemotron.py
  tests/slurm_command_gen_strategy/test_jax_toolbox.py
  tests/test_init.py
Labels: enhancement, Oct24

#262 Improve verify modes
  src/cloudai/cli/handlers.py
  src/cloudai/parser.py
Labels: enhancement, Oct24

#253 Refactor SlurmCommandGenStrategy (_write_sbatch_script)
  src/cloudai/schema/test_template/chakra_replay/slurm_command_gen_strategy.py
  src/cloudai/schema/test_template/jax_toolbox/slurm_command_gen_strategy.py
  src/cloudai/schema/test_template/nccl_test/slurm_command_gen_strategy.py
  src/cloudai/schema/test_template/sleep/slurm_command_gen_strategy.py
  src/cloudai/schema/test_template/ucc_test/slurm_command_gen_strategy.py
  src/cloudai/systems/slurm/strategy/slurm_command_gen_strategy.py
  src/cloudai/test_definitions/gpt.py
  src/cloudai/test_definitions/jax_toolbox.py
  tests/slurm_command_gen_strategy/test_common.py
  tests/slurm_command_gen_strategy/test_jax_toolbox.py
Labels: enhancement, Oct24

#259 Refactor JaxToolboxSlurmCommandGenStrategy unit tests
  tests/slurm_command_gen_strategy/test_jax_toolbox.py
Labels: enhancement, Oct24

#264 Handle node allocation errors gracefully, log details, and exit on failure
  src/cloudai/systems/slurm/slurm_system.py
  tests/conftest.py
  tests/test_slurm_system.py
Labels: bug, enhancement, Oct24

#265 Update NeMo launcher commit hash and image tag
  src/cloudai/test_definitions/nemo_launcher.py
Labels: bug, Oct24

#267 Accept list of tomls as an input for TestParser
  src/cloudai/_core/base_multi_file_parser.py
  src/cloudai/_core/test_parser.py
  src/cloudai/cli/handlers.py
  src/cloudai/parser.py
  tests/test_test_definitions.py
Labels: enhancement, Oct24

#268 Am/verify configs
  .github/workflows/ci.yml
  src/cloudai/_core/test_parser.py
  src/cloudai/cli/cli.py
  src/cloudai/cli/handlers.py
  src/cloudai/parser.py
  tests/test_cli.py
Labels: enhancement, Oct24

#269 Remove deprecated verify modes
  src/cloudai/cli/__init__.py
  src/cloudai/cli/cli.py
  src/cloudai/cli/handlers.py
  tests/test_cli.py
Labels: enhancement, Oct24

#270 Fix bugs in updating the output_path of JaxToolbox cmd_args
  src/cloudai/test_definitions/grok.py
  tests/slurm_command_gen_strategy/test_jax_toolbox.py
Labels: bug, Oct24

#275 Fix README on verify-* modes
  README.md
Labels: bug, documentation, Oct24

#276 Reorganize ReportGenerationStrategy unit tests
  tests/report_generation_strategy/test_jax_toolbox_report_generation_strategy.py
  tests/report_generation_strategy/test_nccl_report_generation_strategy.py
  tests/slurm_command_gen_strategy/test_chakra_replay_slurm_command_gen_strategy.py
  tests/slurm_command_gen_strategy/test_common_slurm_command_gen_strategy.py
  tests/slurm_command_gen_strategy/test_jax_toolbox_slurm_command_gen_strategy.py
  tests/slurm_command_gen_strategy/test_nccl_slurm_command_gen_strategy.py
  tests/slurm_command_gen_strategy/test_nemo_launcher_slurm_command_gen_strategy.py
  tests/slurm_command_gen_strategy/test_sleep_slurm_command_gen_strategy.py
  tests/slurm_command_gen_strategy/test_ucc_slurm_command_gen_strategy.py
Labels: enhancement, Oct24

#277 Rename --output-dir to --results-dir for generate-report command
  README.md
  USER_GUIDE.md
  src/cloudai/cli/cli.py
  src/cloudai/cli/handlers.py
  tests/test_cli.py
Labels: bug, Oct24

#278 List supported tests per each system in README
  README.md
Labels: documentation, Oct24

#279 Remove delay support in dependencies
  USER_GUIDE.md
  conf/common/test_scenario/nccl_test.toml
  conf/common/test_scenario/nemo_launcher.toml
  conf/common/test_scenario/nemo_launcher_with_noise.toml
  conf/common/test_scenario/sleep.toml
  conf/common/test_scenario/ucc_test.toml
  conf/release/spcx/l40s/test_scenario/l40s_bc_nccl_test.toml
  src/cloudai/_core/base_runner.py
  src/cloudai/_core/test_scenario.py
  src/cloudai/_core/test_scenario_parser.py
  tests/test_test_scenario.py
Labels: enhancement, Oct24

#280 Refactor JobStatusRetrievalStrategy unit tests
  tests/job_status_retrieval_strategy/test_jax_toolbox_job_status_retrieval_strategy.py
  tests/job_status_retrieval_strategy/test_nccl_job_status_retrieval_strategy.py
Labels: enhancement, Oct24

#282 Fix bug by removing trailing newline from +cluster.nodelist in command args
  src/cloudai/schema/test_template/nemo_launcher/slurm_command_gen_strategy.py
  tests/slurm_command_gen_strategy/test_nemo_launcher_slurm_command_gen_strategy.py
Labels: bug, Oct24

#284 Remove dead code from `tests/test_parser.py`
  tests/test_parser.py
Labels: enhancement, Oct24

#271 Pr 249 253 bug
  src/cloudai/schema/test_template/jax_toolbox/slurm_command_gen_strategy.py
  tests/slurm_command_gen_strategy/test_jax_toolbox_slurm_command_gen_strategy.py
Labels: bug, Oct24

#287 Update CONTRIBUTING.md to reflect Gitlab->Github migration
  CONTRIBUTING.md
Labels: documentation, Oct24

#286 Use pathlib.Path for TestScenarioParser
  src/cloudai/_core/test_scenario_parser.py
  src/cloudai/parser.py
  tests/test_test_scenario.py
Labels: enhancement, Oct24

#285 Add slurm sbatch generation unit tests
  tests/conftest.py
  tests/ref_data/gpt-no-pretest.sbatch
  tests/ref_data/gpt-pretest.sbatch
  tests/ref_data/gpt.run
  tests/ref_data/grok-no-pretest.sbatch
  tests/ref_data/grok-pretest.sbatch
  tests/ref_data/grok.run
  tests/ref_data/nccl.sbatch
  tests/ref_data/sleep.sbatch
  tests/ref_data/ucc.sbatch
  tests/test_acceptance.py
Labels: enhancement, Oct24

#258 Updates for dev tools and refactoring
  .github/workflows/ci.yml
  requirements-dev.txt
  src/cloudai/_core/test_parser.py
  src/cloudai/systems/kubernetes/kubernetes_system.py
  tests/conftest.py
  tests/report_generation_strategy/test_nccl_report_generation_strategy.py
  tests/slurm_command_gen_strategy/conftest.py
  tests/slurm_command_gen_strategy/test_chakra_replay_slurm_command_gen_strategy.py
  tests/slurm_command_gen_strategy/test_common_slurm_command_gen_strategy.py
  tests/slurm_command_gen_strategy/test_jax_toolbox_slurm_command_gen_strategy.py
  tests/slurm_command_gen_strategy/test_nccl_slurm_command_gen_strategy.py
  tests/slurm_command_gen_strategy/test_nemo_launcher_slurm_command_gen_strategy.py
  tests/slurm_command_gen_strategy/test_sleep_slurm_command_gen_strategy.py
  tests/slurm_command_gen_strategy/test_ucc_slurm_command_gen_strategy.py
  tests/test_acceptance.py
  tests/test_base_installer.py
  tests/test_check_copyright_headers.py
  tests/test_cli.py
  tests/test_csv_report_tool.py
  tests/test_init.py
  tests/test_job_submission_error.py
  tests/test_kubernetes_system.py
  tests/test_parser.py
  tests/test_registry.py
  tests/test_slurm_install_strategy.py
  tests/test_slurm_system.py
  tests/test_standalone_system.py
  tests/test_test_definitions.py
  tests/test_test_scenario.py
  tests/test_toml_files.py
Labels: enhancement

#290 Reduce the number of steps in NeMoLauncher tests
  src/cloudai/test_definitions/nemo_launcher.py
  tests/slurm_command_gen_strategy/test_nemo_launcher_slurm_command_gen_strategy.py
Labels: enhancement, Jan25

#292 Rename TestRun-related var and method in src/cloudai/_core/test_scenario_parser.py
  src/cloudai/_core/test_scenario_parser.py
Labels: enhancement, Jan25

#294 Pass TestRun object into cmd_gen related functions
  src/cloudai/schema/test_template/chakra_replay/slurm_command_gen_strategy.py
  src/cloudai/schema/test_template/jax_toolbox/slurm_command_gen_strategy.py
  src/cloudai/schema/test_template/nccl_test/slurm_command_gen_strategy.py
  src/cloudai/schema/test_template/sleep/slurm_command_gen_strategy.py
  src/cloudai/schema/test_template/ucc_test/slurm_command_gen_strategy.py
  src/cloudai/systems/slurm/strategy/slurm_command_gen_strategy.py
  tests/slurm_command_gen_strategy/test_chakra_replay_slurm_command_gen_strategy.py
  tests/slurm_command_gen_strategy/test_common_slurm_command_gen_strategy.py
  tests/slurm_command_gen_strategy/test_nccl_slurm_command_gen_strategy.py
  tests/slurm_command_gen_strategy/test_sleep_slurm_command_gen_strategy.py
  tests/slurm_command_gen_strategy/test_ucc_slurm_command_gen_strategy.py
Labels: enhancement, Jan25

#295 Always delay job submission to avoid double-booking in slurm
  src/cloudai/_core/base_runner.py
Labels: bug, Oct24
