Repository NVIDIA/cloudai, pull requests merged in 2024-11, with the labels that each got.

#296 Use the latest Chakra replay
  src/cloudai/schema/test_template/chakra_replay/slurm_command_gen_strategy.py
  src/cloudai/test_definitions/chakra_replay.py
  tests/slurm_command_gen_strategy/test_chakra_replay_slurm_command_gen_strategy.py
Labels: enhancement, Jan25

#297 Remove obsolete comment
  src/cloudai/_core/test_template.py
Labels: enhancement, Jan25

#263 Test hook support
  conf/common/test_scenario/nccl_test.toml
  conf/hook/nccl_test.toml
  conf/hook/test/nccl_test_all_gather.toml
  src/cloudai/_core/command_gen_strategy.py
  src/cloudai/_core/test_scenario.py
  src/cloudai/_core/test_scenario_parser.py
  src/cloudai/_core/test_template.py
  src/cloudai/cli/handlers.py
  src/cloudai/parser.py
  src/cloudai/schema/test_template/jax_toolbox/slurm_command_gen_strategy.py
  src/cloudai/schema/test_template/nccl_test/slurm_command_gen_strategy.py
  src/cloudai/systems/slurm/strategy/slurm_command_gen_strategy.py
  src/cloudai/test_definitions/gpt.py
  src/cloudai/test_definitions/grok.py
  src/cloudai/test_definitions/jax_toolbox.py
  tests/ref_data/gpt-no-hook.sbatch
  tests/ref_data/gpt-pre-test.sbatch
  tests/ref_data/grok-no-hook.sbatch
  tests/ref_data/grok-pre-test.sbatch
  tests/ref_data/nccl.sbatch
  tests/ref_data/sleep.sbatch
  tests/ref_data/ucc.sbatch
  tests/slurm_command_gen_strategy/test_common_slurm_command_gen_strategy.py
  tests/slurm_command_gen_strategy/test_jax_toolbox_slurm_command_gen_strategy.py
  tests/test_acceptance.py
  tests/test_parser.py
  tests/test_test_scenario.py
Labels: feature, Jan25

#299 Fix Nemo Launcher cmd generation, add tests
  src/cloudai/schema/test_template/nemo_launcher/slurm_command_gen_strategy.py
  tests/ref_data/nemo-launcher.sbatch
  tests/test_acceptance.py
Labels: bug, Jan25

#302 Use absolute path for NeMo launcher repository
  src/cloudai/schema/test_template/nemo_launcher/slurm_command_gen_strategy.py
Labels: bug, Jan25

#303 Fix broken dry-run mode
  .github/workflows/ci.yml
  src/cloudai/_core/base_runner.py
Labels: bug, Jan25

#304 Check if artifacts installed for dry-run mode
  src/cloudai/cli/handlers.py
Labels: enhancement, Jan25

#305 Update test_acceptance to handle pre-test and non-pre-test cases for nemo-run
  tests/ref_data/nemo-run-no-hook.sbatch
  tests/ref_data/nemo-run-pre-test.sbatch
  tests/test_acceptance.py
Labels: enhancement, Jan25

#306 Update Chakra replay to use tdef
  src/cloudai/schema/test_template/chakra_replay/slurm_command_gen_strategy.py
  tests/slurm_command_gen_strategy/test_chakra_replay_slurm_command_gen_strategy.py
Labels: bug, enhancement, Jan25

#307 Always mount output path for SlurmContainer
  src/cloudai/schema/test_template/slurm_container/slurm_command_gen_strategy.py
  tests/ref_data/slurm_container.sbatch
Labels: enhancement, Jan25

#308 Add sol_path to test scenario
  src/cloudai/_core/test_scenario_parser.py
Labels: bug, Jan25

#309 Always delay job submission to avoid double-booking in slurm
  src/cloudai/_core/base_runner.py
Labels: bug, Jan25

#300 Use TestDefinion in strategies instead of TestTemplate
  src/cloudai/__init__.py
  src/cloudai/_core/registry.py
  src/cloudai/_core/test_parser.py
  src/cloudai/schema/test_template/chakra_replay/__init__.py
  src/cloudai/schema/test_template/chakra_replay/template.py
  src/cloudai/schema/test_template/jax_toolbox/__init__.py
  src/cloudai/schema/test_template/jax_toolbox/template.py
  src/cloudai/schema/test_template/nccl_test/__init__.py
  src/cloudai/schema/test_template/nccl_test/template.py
  src/cloudai/schema/test_template/nemo_launcher/__init__.py
  src/cloudai/schema/test_template/nemo_launcher/template.py
  src/cloudai/schema/test_template/nemo_run/__init__.py
  src/cloudai/schema/test_template/nemo_run/template.py
  src/cloudai/schema/test_template/sleep/__init__.py
  src/cloudai/schema/test_template/sleep/template.py
  src/cloudai/schema/test_template/slurm_container/template.py
  src/cloudai/schema/test_template/ucc_test/__init__.py
  src/cloudai/schema/test_template/ucc_test/template.py
  tests/slurm_command_gen_strategy/test_jax_toolbox_slurm_command_gen_strategy.py
  tests/test_acceptance.py
  tests/test_init.py
  tests/test_registry.py
Labels: enhancement, Jan25
