Repository NVIDIA/cloudai, pull requests merged in 2024-09, with the labels that each got.

#171 Add Nemotron model via PAXML to CloudAI + optimization for large GPU runs
  src/cloudai/_core/test_template_parser.py
  src/cloudai/schema/test_template/jax_toolbox/job_status_retrieval_strategy.py
  src/cloudai/schema/test_template/jax_toolbox/slurm_command_gen_strategy.py
  tests/test_job_status_retrieval_strategy.py
  tests/test_slurm_command_gen_strategy.py
Labels: Oct24, feature

#186 Update NCCL Test Templates and Introduce Kubernetes-Specific Strategies
  src/cloudai/__init__.py
  src/cloudai/_core/base_runner.py
  src/cloudai/runner/kubernetes/kubernetes_runner.py
  src/cloudai/schema/test_template/nccl_test/__init__.py
  src/cloudai/schema/test_template/nccl_test/kubernetes_json_gen_strategy.py
  src/cloudai/systems/kubernetes/kubernetes_system.py
  tests/test_init.py
Labels: Oct24, feature

#189 add test for the reservation feature
  tests/test_slurm_command_gen_strategy.py
Labels: Oct24, feature

#190 Add missing k8s package into package dependencies.
  pyproject.toml
  tests/test_package.py
Labels: bug, Oct24

#191 Fix test directory name typo in README.md
  README.md
Labels: documentation

#188 Fix bug in generating NCCL test reports on K8s
  src/cloudai/__init__.py
  tests/test_init.py
Labels: bug, Oct24

#192 Log Runner Initialization with Run Mode Indication in BaseRunner
  src/cloudai/_core/runner.py
Labels: enhancement, Oct24

#193 Use Host Network for Kubernetes NCCL Tests
  src/cloudai/schema/test_template/nccl_test/kubernetes_json_gen_strategy.py
Labels: enhancement, Oct24

#158 Use Pydantic to verify System schemas
  README.md
  conf/common/system/example_slurm_cluster.toml
  pyproject.toml
  requirements.txt
  src/cloudai/__init__.py
  src/cloudai/__main__.py
  src/cloudai/_core/registry.py
  src/cloudai/_core/system_parser.py
  src/cloudai/parser.py
  src/cloudai/parser/__init__.py
  src/cloudai/parser/system_parser/kubernetes_system_parser.py
  src/cloudai/parser/system_parser/slurm_system_parser.py
  src/cloudai/parser/system_parser/standalone_system_parser.py
  src/cloudai/systems/kubernetes/kubernetes_system.py
  src/cloudai/systems/slurm/__init__.py
  src/cloudai/systems/slurm/slurm_node.py
  src/cloudai/systems/slurm/slurm_system.py
  src/cloudai/systems/standalone_system.py
  tests/conftest.py
  tests/test_acceptance.py
  tests/test_base_installer.py
  tests/test_init.py
  tests/test_job_submission_error.py
  tests/test_parser.py
  tests/test_registry.py
  tests/test_slurm_command_gen_strategy.py
  tests/test_slurm_install_strategy.py
  tests/test_slurm_system.py
  tests/test_slurm_system_parser.py
  tests/test_standalone_system.py
  tests/test_toml_files.py
Labels: Oct24, feature

#173 Feature group all
  USER_GUIDE.md
  src/cloudai/systems/slurm/slurm_system.py
  tests/test_slurm_system.py
Labels: Oct24, feature

#201 Exclude abstract methods from coverage
  pyproject.toml
Labels: enhancement, Oct24

#145 Introduce Pydantic to verify Test schema
  README.md
  USER_GUIDE.md
  conf/common/test/chakra_replay.toml
  conf/common/test/gpt.toml
  conf/common/test/llama.toml
  conf/common/test/nccl_test_all_gather.toml
  conf/common/test/nccl_test_all_reduce.toml
  conf/common/test/nccl_test_alltoall.toml
  conf/common/test/nccl_test_reduce_scatter.toml
  conf/common/test_template/nccl_test.toml
  conf/common/test_template/nemo_launcher.toml
  conf/release/spcx/l40s/test/l40s-bc-nccl_test_all_gather.toml
  conf/release/spcx/l40s/test/l40s-bc-nccl_test_all_gather_worst.toml
  conf/release/spcx/l40s/test/l40s-bc-nccl_test_all_reduce.toml
  conf/release/spcx/l40s/test/l40s-bc-nccl_test_all_reduce_worst.toml
  conf/release/spcx/l40s/test/l40s-bc-nccl_test_alltoall.toml
  conf/release/spcx/l40s/test/l40s-bc-nccl_test_alltoall_worst.toml
  conf/release/spcx/l40s/test/l40s-bc-nccl_test_alltoall_worst_failover.toml
  conf/release/spcx/l40s/test/l40s-bc-nccl_test_bisection.toml
  conf/release/spcx/l40s/test/l40s-bc-nccl_test_reduce_scatter.toml
  conf/release/spcx/l40s/test/l40s-bc-nccl_test_reduce_scatter_worst.toml
  conf/release/spcx/l40s/test/l40s-bc-nccl_test_sendrecv.toml
  conf/release/spcx/l40s/test/l40s-bc-nccl_test_sendrecv_worst.toml
  pyproject.toml
  src/cloudai/__init__.py
  src/cloudai/__main__.py
  src/cloudai/_core/base_multi_file_parser.py
  src/cloudai/_core/exceptions.py
  src/cloudai/_core/registry.py
  src/cloudai/_core/test.py
  src/cloudai/_core/test_parser.py
  src/cloudai/_core/test_template_parser.py
  src/cloudai/parser.py
  src/cloudai/schema/test_template/jax_toolbox/slurm_command_gen_strategy.py
  src/cloudai/schema/test_template/nemo_launcher/slurm_install_strategy.py
  src/cloudai/systems/slurm/strategy/slurm_command_gen_strategy.py
  src/cloudai/systems/slurm/strategy/slurm_install_strategy.py
  src/cloudai/test_definitions/__init__.py
  src/cloudai/test_definitions/chakra.py
  src/cloudai/test_definitions/nccl.py
  src/cloudai/test_definitions/nemo_launcher.py
  src/cloudai/test_definitions/sleep.py
  src/cloudai/test_definitions/ucc.py
  tests/test_acceptance.py
  tests/test_check_copyright_headers.py
  tests/test_init.py
  tests/test_parser.py
  tests/test_registry.py
  tests/test_slurm_command_gen_strategy.py
  tests/test_test_definitions.py
  tests/test_toml_files.py
Labels: Oct24, feature

#204 Extend CI for high level use cases
  .github/workflows/ci.yml
Labels: enhancement, Oct24

#209 Replace 'training.values' Key with 'training' in final_cmd_args
  src/cloudai/schema/test_template/nemo_launcher/slurm_command_gen_strategy.py
Labels: bug, Oct24

#206 Use System Install Path Instead of Local Member Variables
  src/cloudai/_core/test_template_strategy.py
  src/cloudai/schema/test_template/jax_toolbox/slurm_install_strategy.py
  src/cloudai/schema/test_template/nccl_test/slurm_install_strategy.py
  src/cloudai/schema/test_template/nemo_launcher/slurm_command_gen_strategy.py
  src/cloudai/schema/test_template/nemo_launcher/slurm_install_strategy.py
  src/cloudai/schema/test_template/ucc_test/slurm_install_strategy.py
Labels: enhancement, Oct24

#207 Remove Unused env_vars From Initialization Code
  src/cloudai/_core/command_gen_strategy.py
  src/cloudai/_core/json_gen_strategy.py
  src/cloudai/_core/test.py
  src/cloudai/_core/test_parser.py
  src/cloudai/_core/test_scenario_parser.py
  src/cloudai/_core/test_template.py
  src/cloudai/_core/test_template_strategy.py
  src/cloudai/schema/test_template/chakra_replay/slurm_command_gen_strategy.py
  src/cloudai/schema/test_template/jax_toolbox/slurm_command_gen_strategy.py
  src/cloudai/schema/test_template/nccl_test/kubernetes_json_gen_strategy.py
  src/cloudai/schema/test_template/nccl_test/slurm_command_gen_strategy.py
  src/cloudai/schema/test_template/nemo_launcher/slurm_command_gen_strategy.py
  src/cloudai/schema/test_template/nemo_launcher/slurm_install_strategy.py
  src/cloudai/schema/test_template/sleep/kubernetes_json_gen_strategy.py
  src/cloudai/schema/test_template/sleep/slurm_command_gen_strategy.py
  src/cloudai/schema/test_template/sleep/standalone_command_gen_strategy.py
  src/cloudai/schema/test_template/ucc_test/slurm_command_gen_strategy.py
  src/cloudai/systems/slurm/strategy/slurm_command_gen_strategy.py
  src/cloudai/systems/slurm/strategy/slurm_install_strategy.py
  tests/test_slurm_command_gen_strategy.py
  tests/test_slurm_install_strategy.py
Labels: enhancement, Oct24

#211 Remove Config File Handling and TOML Dependency from SlurmInstaller
  src/cloudai/installer/slurm_installer.py
Labels: bug, Oct24

#212 Fix Bug in DockerImageCacheResult to Correctly Retrieve Absolute Paths
  src/cloudai/util/docker_image_cache_manager.py
  tests/test_docker_image_cache_manager.py
Labels: bug, Oct24

#210 Add Support for Cluster Account and gpus_per_node in Command Generation
  src/cloudai/schema/test_template/nemo_launcher/slurm_command_gen_strategy.py
  tests/test_slurm_command_gen_strategy.py
Labels: bug, Oct24

#213 Disabling dataset check during Nemo launcher installation
  src/cloudai/schema/test_template/nemo_launcher/slurm_install_strategy.py
  tests/test_slurm_install_strategy.py
Labels: enhancement, Oct24

#216 Enhance Error Handling for Missing default_partition
  src/cloudai/systems/slurm/strategy/slurm_command_gen_strategy.py
  tests/test_slurm_command_gen_strategy.py
Labels: enhancement, Oct24

#215 Remove Dead Code by Eliminating Unused `install_path`
  src/cloudai/systems/slurm/strategy/slurm_command_gen_strategy.py
Labels: enhancement, Oct24

#218 Remove unnecessary permission checks and exception handling in NeMoLauncherSlurmInstallStrategy
  src/cloudai/schema/test_template/nemo_launcher/slurm_install_strategy.py
Labels: enhancement, Oct24
