Repository NVIDIA/cloudai, pull requests merged in 2024-06, with the labels that each got.

#76 Handle boolean and string values for `cache_docker_images_locally`
  src/cloudai/parser/system_parser/slurm_system_parser.py
  tests/test_slurm_system_parser.py
Labels: bug, enhancement

#69 Use DockerImageCacheManager in CommandGenStrategy
  src/cloudai/schema/test_template/nccl_test/slurm_command_gen_strategy.py
  src/cloudai/schema/test_template/nemo_launcher/slurm_command_gen_strategy.py
  src/cloudai/schema/test_template/ucc_test/slurm_command_gen_strategy.py
  src/cloudai/systems/slurm/strategy/slurm_command_gen_strategy.py
  tests/test_slurm_command_gen_strategy.py
Labels: bug

#75 Update `_clone_repository` to handle existing repository path
  src/cloudai/schema/test_template/nemo_launcher/slurm_install_strategy.py
  tests/test_slurm_install_strategy.py
Labels: bug

#77 Remove redundant installation check from run mode
  src/cloudai/__main__.py
Labels: enhancement

#78 Fix bug in `_check_docker_image_accessibility`
  requirements.txt
  src/cloudai/util/docker_image_cache_manager.py
  tests/test_docker_image_cache_manager.py
Labels: bug

#74 Update CI tool to include tests directory and add copyright notices
  ci_tools/check_copyright_headers.py
  src/cloudai/schema/test_template/jax_toolbox/job_status_retrieval_strategy.py
  tests/test_acceptance.py
  tests/test_base_installer.py
  tests/test_docker_image_cache_manager.py
  tests/test_init.py
  tests/test_job_status_retrieval_strategy.py
  tests/test_job_submission_error.py
  tests/test_registry.py
  tests/test_report_generation_strategy.py
  tests/test_slurm_command_gen_strategy.py
  tests/test_slurm_install_strategy.py
  tests/test_slurm_system.py
  tests/test_slurm_system_parser.py
Labels: bug

#81 Add credentials for NGC to README
  README.md
Labels: documentation

#39 Update NCCL test_template container
  conf/v0.6/general/test_template/nccl_test.toml
Labels: enhancement

#37 Update UCC test_template container
  conf/v0.6/general/test_template/ucc_test.toml
Labels: enhancement

#73 Use logging.config and do not pass CLI args as a parameter
  src/cloudai/__main__.py
  src/cloudai/_core/base_installer.py
  src/cloudai/_core/base_runner.py
  src/cloudai/_core/grader.py
  src/cloudai/_core/parser.py
  src/cloudai/_core/runner.py
  src/cloudai/_core/test_scenario.py
  src/cloudai/_core/test_template.py
  src/cloudai/_core/test_template_parser.py
  src/cloudai/installer/installer.py
  src/cloudai/installer/slurm_installer.py
  src/cloudai/report_generator/report_generator.py
  src/cloudai/runner/slurm/slurm_runner.py
  src/cloudai/runner/standalone/standalone_runner.py
  src/cloudai/schema/test_template/nemo_launcher/slurm_install_strategy.py
  src/cloudai/systems/slurm/slurm_system.py
  src/cloudai/util/docker_image_cache_manager.py
  tests/test_acceptance.py
Labels: enhancement

#85 Fix bug in check_docker_image_exists to correctly prioritize cached files
  src/cloudai/util/docker_image_cache_manager.py
  tests/test_docker_image_cache_manager.py
Labels: bug

#89 Update docstring to comply with coding style and max column length
  src/cloudai/_core/base_system_parser.py
  src/cloudai/_core/grader.py
  src/cloudai/_core/grading_strategy.py
  src/cloudai/_core/parser.py
  src/cloudai/_core/system.py
  src/cloudai/_core/system_parser.py
  src/cloudai/_core/test_parser.py
  src/cloudai/_core/test_scenario.py
  src/cloudai/_core/test_scenario_parser.py
  src/cloudai/_core/test_template_strategy.py
  src/cloudai/parser/system_parser/standalone_system_parser.py
  src/cloudai/report_generator/report_generator.py
  src/cloudai/runner/slurm/slurm_runner.py
  src/cloudai/runner/standalone/standalone_runner.py
  src/cloudai/schema/test_template/common/slurm_job_id_retrieval_strategy.py
  src/cloudai/schema/test_template/common/standalone_job_id_retrieval_strategy.py
  src/cloudai/schema/test_template/jax_toolbox/slurm_command_gen_strategy.py
  src/cloudai/schema/test_template/nccl_test/grading_strategy.py
  src/cloudai/schema/test_template/nemo_launcher/grading_strategy.py
  src/cloudai/schema/test_template/nemo_launcher/slurm_job_id_retrieval_strategy.py
  src/cloudai/schema/test_template/nemo_launcher/template.py
  src/cloudai/schema/test_template/sleep/grading_strategy.py
  src/cloudai/schema/test_template/sleep/standalone_command_gen_strategy.py
  src/cloudai/schema/test_template/sleep/standalone_install_strategy.py
  src/cloudai/schema/test_template/ucc_test/grading_strategy.py
  src/cloudai/systems/slurm/slurm_node.py
  src/cloudai/systems/slurm/slurm_system.py
  src/cloudai/systems/slurm/strategy/slurm_command_gen_strategy.py
  src/cloudai/util/command_shell.py
Labels: documentation

#90 Fix parsing logic and add unit tests for NCCL test report generation
  src/cloudai/schema/test_template/nccl_test/report_generation_strategy.py
  tests/test_slurm_report_generation_strategy.py
Labels: bug

#83 New CLI args and filter tests templates for installation
  README.md
  src/cloudai/__init__.py
  src/cloudai/__main__.py
  src/cloudai/_core/base_installer.py
  src/cloudai/_core/base_multi_file_parser.py
  src/cloudai/_core/parser.py
  src/cloudai/_core/test.py
  src/cloudai/_core/test_parser.py
  src/cloudai/_core/test_template_parser.py
  src/cloudai/installer/installer.py
  src/cloudai/installer/slurm_installer.py
  tests/test_acceptance.py
  tests/test_base_installer.py
  tests/test_parser.py
Labels: enhancement

#93 Improve overall performance
  pyproject.toml
  src/cloudai/report_generator/tool/tensorboard_data_reader.py
Labels: enhancement

#94 Update README with project goals, supported systems, and key concepts
  README.md
Labels: documentation

#95 Make logging a bit more conscious
  src/cloudai/__main__.py
  src/cloudai/_core/base_installer.py
  src/cloudai/_core/base_runner.py
  src/cloudai/schema/test_template/nemo_launcher/slurm_install_strategy.py
  src/cloudai/systems/slurm/slurm_system.py
  src/cloudai/util/docker_image_cache_manager.py
Labels: enhancement

#98 Refactor _check_docker_image_accessibility to remove srun usage
  src/cloudai/util/docker_image_cache_manager.py
  tests/test_docker_image_cache_manager.py
Labels: bug

#100 Update NcclTestJobStatusRetrievalStrategy to improve error messages
  src/cloudai/schema/test_template/nccl_test/job_status_retrieval_strategy.py
  tests/test_job_status_retrieval_strategy.py
Labels: enhancement

#101 Update JaxToolboxJobStatusRetrievalStrategy to improve error messages
  src/cloudai/schema/test_template/jax_toolbox/job_status_retrieval_strategy.py
  tests/test_job_status_retrieval_strategy.py
Labels: enhancement

#102 Bump version to v0.7.7
  pyproject.toml
Labels: enhancement

#103 Handle 401 Unauthorized error with detailed instructions for Docker image access
  src/cloudai/util/docker_image_cache_manager.py
  tests/test_docker_image_cache_manager.py
Labels: enhancement

#107 Fix _check_docker_image_accessibility condition and add detailed logging
  src/cloudai/util/docker_image_cache_manager.py
  tests/test_docker_image_cache_manager.py
Labels: bug

#105 Refactor handle_install_and_uninstall to identify unique test templates
  src/cloudai/__main__.py
  src/cloudai/_core/base_installer.py
  src/cloudai/installer/installer.py
  src/cloudai/installer/slurm_installer.py
  tests/test_acceptance.py
  tests/test_base_installer.py
Labels: bug

#109 Update USER_GUIDE
  USER_GUIDE.md
  src/cloudai/__main__.py
  src/cloudai/report_generator/report_generator.py
Labels: documentation

#113 Remove bisection tests from NCCL-test template
  conf/test/nccl_test_bisection.toml
  conf/test_scenario/nccl_test.toml
  conf/test_scenario/nemo_launcher_with_noise.toml
  conf/test_template/nccl_test.toml
  src/cloudai/schema/test_template/nccl_test/template.py
Labels: bug

#112 Fix bug in NeMo launcher report generation
  src/cloudai/schema/test_template/nemo_launcher/report_generation_strategy.py
Labels: bug

#111 Add pip install requirements.txt step to NeMoLauncherSlurmInstallStrategy
  src/cloudai/schema/test_template/nemo_launcher/slurm_install_strategy.py
  tests/test_slurm_install_strategy.py
Labels: bug

#99 Enhance Quick Start guide for Docker repo access and API key
  README.md
Labels: documentation
