Repository NVIDIA/cloudai, pull requests merged in 2024-07, with the labels that each got.

#118 Add pyxis mktemp error handling and test cases in JaxToolbox strategy
  src/cloudai/schema/test_template/jax_toolbox/job_status_retrieval_strategy.py
  tests/test_job_status_retrieval_strategy.py
Labels: enhancement

#116 Add section on downloading NeMo datasets to USER_GUIDE.md
  USER_GUIDE.md
Labels: documentation

#120 Enhance USER_GUIDE.md with system schema description and troubleshooting steps
  USER_GUIDE.md
Labels: documentation

#124 Fix bug in generating NeMo launcher command
  src/cloudai/schema/test_template/nemo_launcher/slurm_command_gen_strategy.py
Labels: bug

#123 Add section on describing a test scenario to USER_GUIDE.md
  USER_GUIDE.md
Labels: documentation

#125 Add `cache_docker_images_locally` field to system schema in USER_GUIDE.md
  USER_GUIDE.md
Labels: documentation

#126 Allow local docker image caching for JaxToolbox
  src/cloudai/schema/test_template/jax_toolbox/slurm_command_gen_strategy.py
  src/cloudai/schema/test_template/jax_toolbox/slurm_install_strategy.py
Labels: enhancement

#119 Update BaseRunner to include scenario name in output directory
  .github/workflows/ci.yml
  pyproject.toml
  src/cloudai/_core/base_runner.py
  tests/test_base_runner.py
Labels: enhancement

#127 Add mpi field to SlurmSystem and allow different MPI options in schema
  USER_GUIDE.md
  conf/system/example_slurm_cluster.toml
  src/cloudai/parser/system_parser/slurm_system_parser.py
  src/cloudai/schema/test_template/chakra_replay/slurm_command_gen_strategy.py
  src/cloudai/schema/test_template/jax_toolbox/slurm_command_gen_strategy.py
  src/cloudai/schema/test_template/nccl_test/slurm_command_gen_strategy.py
  src/cloudai/schema/test_template/ucc_test/slurm_command_gen_strategy.py
  src/cloudai/systems/slurm/slurm_system.py
  src/cloudai/systems/slurm/strategy/slurm_command_gen_strategy.py
  tests/test_slurm_system_parser.py
Labels: bug

#131 Update logging to use dynamic log file name from args.log_file in run mode
  src/cloudai/__main__.py
  tests/test_acceptance.py
Labels: bug

#132 Update README: add mandatory args test-templates-dir and tests-dir
  README.md
Labels: bug, documentation

#135 Update NeMo launcher troubleshooting guide for clarity and conciseness
  USER_GUIDE.md
Labels: documentation

#121 Add support for Sleep on Slurm systems
  src/cloudai/__init__.py
  src/cloudai/schema/test_template/sleep/__init__.py
  src/cloudai/schema/test_template/sleep/slurm_command_gen_strategy.py
  tests/test_init.py
Labels: bug

#137 Raise descriptive exceptions when strategies are missing
  src/cloudai/_core/test_template.py
Labels: enhancement

#142 Added JaxToolbox (Grok) troubleshooting steps
  USER_GUIDE.md
Labels: documentation

#136 Improve tokenizer path handling in NeMo Launcher Slurm strategy
  src/cloudai/schema/test_template/nemo_launcher/slurm_command_gen_strategy.py
  tests/test_slurm_command_gen_strategy.py
Labels: enhancement

#143 Remove identical if-else branches
  src/cloudai/_core/test_template_parser.py
Labels: bug

#140 Move parts of srun CLI generation into base class
  pyproject.toml
  src/cloudai/schema/test_template/chakra_replay/slurm_command_gen_strategy.py
  src/cloudai/schema/test_template/jax_toolbox/slurm_command_gen_strategy.py
  src/cloudai/schema/test_template/nccl_test/slurm_command_gen_strategy.py
  src/cloudai/schema/test_template/sleep/slurm_command_gen_strategy.py
  src/cloudai/schema/test_template/ucc_test/slurm_command_gen_strategy.py
  src/cloudai/systems/slurm/strategy/slurm_command_gen_strategy.py
  tests/test_slurm_command_gen_strategy.py
Labels: enhancement

#149 Make sure to dry-run all tests in a test scenario
  src/cloudai/_core/base_runner.py
  tests/test_acceptance.py
Labels: bug

#148 Add warning for insufficient epochs in JaxToolbox report generation
  src/cloudai/schema/test_template/jax_toolbox/report_generation_strategy.py
Labels: documentation

#147 Remove subtest name check in NcclTestSlurmCommandGenStrategy
  src/cloudai/schema/test_template/nccl_test/slurm_command_gen_strategy.py
  src/cloudai/schema/test_template/nccl_test/template.py
Labels: bug, enhancement

#150 Handle disk quota exceeded error in cache_docker_image method
  src/cloudai/util/docker_image_cache_manager.py
  tests/test_docker_image_cache_manager.py
Labels: bug

#152 Enhance error messages to provide guidance for missing schemas
  src/cloudai/_core/test_parser.py
  src/cloudai/_core/test_scenario_parser.py
Labels: documentation

#156 Enhance job status error message for clarity and user guidance
  src/cloudai/systems/slurm/slurm_system.py
Labels: documentation

#160 Allow extra srun args set in system config
  src/cloudai/parser/system_parser/slurm_system_parser.py
  src/cloudai/schema/test_template/jax_toolbox/slurm_command_gen_strategy.py
  src/cloudai/schema/test_template/sleep/slurm_command_gen_strategy.py
  src/cloudai/systems/slurm/slurm_system.py
  src/cloudai/systems/slurm/strategy/slurm_command_gen_strategy.py
  tests/test_slurm_command_gen_strategy.py
Labels: enhancement

#162 Automatically define version from the git tags
  pyproject.toml
Labels: enhancement

#161 add support for NeMo Launcher in the reservation
  src/cloudai/schema/test_template/nemo_launcher/slurm_command_gen_strategy.py
  tests/test_slurm_command_gen_strategy.py
Labels: enhancement
