Repository NVIDIA/cloudai, pull requests merged in 2025-08, with the labels that each got.

#616 Preserve the order of environment variables specified in the system schema
  src/cloudai/systems/slurm/slurm_command_gen_strategy.py
  tests/ref_data/nemo-run-no-hook.sbatch
  tests/ref_data/nemo-run-pre-test.sbatch
  tests/ref_data/nemo-run-vboost.sbatch
  tests/ref_data/nixl-perftest.sbatch
  tests/ref_data/triton-inference.sbatch
  tests/test_slurm_system.py
Labels: bug

#627 Replace PyTorch image tag from 24.02-py3 to 25.06-py3 in all conf TOML files
  conf/common/test/dse_nccl_all_gather.toml
  conf/common/test/nccl_test.toml
  conf/common/test/nccl_test_all_gather.toml
  conf/common/test/ucc_test.toml
  conf/common/test_scenario/nccl_test.toml
  conf/hook/test/nccl_test_all_gather.toml
  conf/release/nemo_acceptance/test/nccl_test_all_reduce_loopback.toml
  conf/release/spcx/l40s/test/l40s-bc-nccl_test_all_gather.toml
  conf/release/spcx/l40s/test/l40s-bc-nccl_test_all_gather_worst.toml
  conf/release/spcx/l40s/test/l40s-bc-nccl_test_all_reduce.toml
  conf/release/spcx/l40s/test/l40s-bc-nccl_test_all_reduce_worst.toml
  conf/release/spcx/l40s/test/l40s-bc-nccl_test_alltoall.toml
  conf/release/spcx/l40s/test/l40s-bc-nccl_test_alltoall_worst.toml
  conf/release/spcx/l40s/test/l40s-bc-nccl_test_alltoall_worst_failover.toml
  conf/release/spcx/l40s/test/l40s-bc-nccl_test_bisection.toml
  conf/release/spcx/l40s/test/l40s-bc-nccl_test_broadcast.toml
  conf/release/spcx/l40s/test/l40s-bc-nccl_test_gather.toml
  conf/release/spcx/l40s/test/l40s-bc-nccl_test_hypercube.toml
  conf/release/spcx/l40s/test/l40s-bc-nccl_test_reduce.toml
  conf/release/spcx/l40s/test/l40s-bc-nccl_test_reduce_scatter.toml
  conf/release/spcx/l40s/test/l40s-bc-nccl_test_reduce_scatter_worst.toml
  conf/release/spcx/l40s/test/l40s-bc-nccl_test_scatter.toml
  conf/release/spcx/l40s/test/l40s-bc-nccl_test_sendrecv.toml
  conf/release/spcx/l40s/test/l40s-bc-nccl_test_sendrecv_worst.toml
Labels: bug

#628 Update doc/ai_dynamo.md
  doc/ai_dynamo.md
Labels: documentation

#626 Replace Nemo image tag from 24.12.rc3 to 25.04.rc2 in all conf TOML files
  conf/experimental/test/nemo_launcher_nemotron_15b_bf16_128_node.toml
  conf/experimental/test/nemo_launcher_nemotron_15b_bf16_256_node.toml
  conf/experimental/test/nemo_launcher_nemotron_15b_bf16_2_node.toml
  conf/experimental/test/nemo_launcher_nemotron_15b_fp8_128_node.toml
  conf/experimental/test/nemo_launcher_nemotron_15b_fp8_16_node.toml
  conf/experimental/test/nemo_launcher_nemotron_15b_fp8_256_node.toml
  conf/experimental/test/nemo_launcher_nemotron_15b_fp8_2_node.toml
  conf/experimental/test/nemo_launcher_nemotron_15b_fp8_32_node.toml
  conf/experimental/test/nemo_launcher_nemotron_15b_fp8_4_node.toml
  conf/experimental/test/nemo_launcher_nemotron_15b_fp8_64_node.toml
  conf/experimental/test/nemo_launcher_nemotron_15b_fp8_8_node.toml
Labels: bug, enhancement

#629 Improve prepare_output_dir error handling for permissions and read-only fs
  src/cloudai/util/__init__.py
  tests/test_base_installer.py
Labels: bug

#631 Improve prepare_output_dir error handling for permissions and read-only fs (continued)
  tests/test_base_installer.py
Labels: bug, enhancement

#615 Use a shell script as the entry point for AI Dynamo
  src/cloudai/models/scenario.py
  src/cloudai/test_scenario_parser.py
  src/cloudai/workloads/ai_dynamo/__init__.py
  src/cloudai/workloads/ai_dynamo/ai_dynamo.py
  src/cloudai/workloads/ai_dynamo/ai_dynamo.sh
  src/cloudai/workloads/ai_dynamo/slurm_command_gen_strategy.py
  tests/ref_data/ai-dynamo.sbatch
  tests/report_generation_strategy/test_ai_dynamo_report_generation_strategy.py
  tests/slurm_command_gen_strategy/test_ai_dynamo_slurm_command_gen_strategy.py
  tests/test_acceptance.py
Labels: feature

#620 Handle multi-section CSV format in AI Dynamo report generation
  src/cloudai/workloads/ai_dynamo/report_generation_strategy.py
  tests/report_generation_strategy/test_ai_dynamo_report_generation_strategy.py
Labels: bug, enhancement

#617 Log mapping between AI Dynamo nodes and roles
  src/cloudai/workloads/ai_dynamo/ai_dynamo.sh
Labels: feature

#643 Preserve installables' state during apply_params_set()
  src/cloudai/_core/test_scenario.py
  tests/test_cloudaigym.py
Labels: bug

#642 Control which env vars dumped for per-rand evaluation
  src/cloudai/workloads/nixl_bench/slurm_command_gen_strategy.py
Labels: bug, enhancement

#646 Update USER_GUIDE.md
  USER_GUIDE.md
Labels: bug, documentation

#653 Follow-up for PR641 (Support for DeepSeekR1 model with SGLang / AI Dynamo)
  src/cloudai/workloads/ai_dynamo/ai_dynamo.sh
Labels: enhancement

#657 Refactor GPU count to use _gpus_per_node in vllm and env validation
  src/cloudai/workloads/ai_dynamo/ai_dynamo.sh
Labels: enhancement

#655 Mount huggingface_home_container_path unconditionally
  src/cloudai/workloads/ai_dynamo/slurm_command_gen_strategy.py
Labels: enhancement

#666 Handle single-sbatch metadata layout in report
  src/cloudai/reporter.py
  tests/test_reporter.py
Labels: bug

#668 Support two NIXL bench output formats
  src/cloudai/workloads/nixl_bench/report_generation_strategy.py
  tests/report_generation_strategy/test_nixl_bench_report.py
Labels: enhancement

#659 Add error detection and retry mechanism for worker failures
  src/cloudai/workloads/ai_dynamo/ai_dynamo.sh
  src/cloudai/workloads/ai_dynamo/slurm_command_gen_strategy.py
  tests/ref_data/ai-dynamo.sbatch
Labels: enhancement

#670 Use single source of data for reporting and NIXL pass/fail
  src/cloudai/workloads/nixl_bench/nixl_bench.py
  src/cloudai/workloads/nixl_bench/report_generation_strategy.py
  tests/job_status_retrieval_strategy/test_nixlbench_job_status_retrieval_strategy.py
  tests/report_generation_strategy/test_nixl_bench_report.py
Labels: bug, enhancement

#673 Update NIXL bench command generation logic
  src/cloudai/workloads/nixl_bench/slurm_command_gen_strategy.py
  tests/ref_data/nixl_bench.sbatch
  tests/slurm_command_gen_strategy/test_nixl_bench_slurm_command_gen_strategy.py
  tests/test_acceptance.py
Labels: enhancement

#675 Make agent_reward_function configurable
  src/cloudai/models/scenario.py
Labels: bug

#676 Auto install missing components for workloads in run mode
  src/cloudai/_core/base_installer.py
  src/cloudai/cli/handlers.py
Labels: enhancement
