Repository NVIDIA/cloudai, pull requests merged in 2025-09, with the labels that each got.

#681 Update Nemo image reference to nvcr.io#nvidia/nemo:25.07 in all toml files
  conf/common/test/dse_nemo_run_llama3_8b_bf16.toml
  conf/common/test/dse_nemo_run_llama3_8b_fp8.toml
  conf/common/test/nemo_run_llama3_8b.toml
  conf/experimental/test/nemo_launcher_nemotron_15b_bf16_128_node.toml
  conf/experimental/test/nemo_launcher_nemotron_15b_bf16_256_node.toml
  conf/experimental/test/nemo_launcher_nemotron_15b_bf16_2_node.toml
  conf/experimental/test/nemo_launcher_nemotron_15b_fp8_128_node.toml
  conf/experimental/test/nemo_launcher_nemotron_15b_fp8_16_node.toml
  conf/experimental/test/nemo_launcher_nemotron_15b_fp8_256_node.toml
  conf/experimental/test/nemo_launcher_nemotron_15b_fp8_2_node.toml
  conf/experimental/test/nemo_launcher_nemotron_15b_fp8_32_node.toml
  conf/experimental/test/nemo_launcher_nemotron_15b_fp8_4_node.toml
  conf/experimental/test/nemo_launcher_nemotron_15b_fp8_64_node.toml
  conf/experimental/test/nemo_launcher_nemotron_15b_fp8_8_node.toml
  conf/release/nemo_acceptance/test/nemo_run_llama3_8b.toml
Labels: enhancement

#682 Increase time limit to 60m in conf/common/test_scenario/dse_nemo_run_llama3_8b.toml
  conf/common/test_scenario/dse_nemo_run_llama3_8b.toml
Labels: bug

#686 Add documentation for workloads
  .github/workflows/ci.yml
  doc/conf.py
  doc/index.md
  doc/workloads/ai_dynamo.rst
  doc/workloads/bash_cmd.rst
  doc/workloads/chakra_replay.rst
  doc/workloads/index.md
  doc/workloads/nccl.rst
  doc/workloads/nemo_run.rst
  doc/workloads/nixl_bench.rst
  doc/workloads/nixl_kvbench.rst
  doc/workloads/nixl_perftest.rst
  doc/workloads/sleep.rst
  doc/workloads/slurm_container.rst
  pyproject.toml
Labels: documentation

#687 Explicitly forbid dependencies for scenarios with DSE jobs
  src/cloudai/cli/handlers.py
  tests/test_handlers.py
Labels: bug

#690 Fix NIXL bench output parsing in case of noisy output
  README.md
  USER_GUIDE.md
  doc/index.md
  doc/workloads/index.md
  src/cloudai/workloads/common/nixl.py
  tests/report_generation_strategy/test_nixl_bench_report.py
Labels: bug

#691 Add more documentation
  doc/USER_GUIDE.md
  doc/workloads/ucc.rst
Labels: documentation

#677 Re-work CLI implementation to use Click
  pyproject.toml
  src/cloudai/__main__.py
  src/cloudai/cli/__init__.py
  src/cloudai/cli/cli.py
  tests/test_acceptance.py
  tests/test_cli.py
Labels: feature

#700 Fix install/uninstall commands examples in doc
  README.md
  doc/index.md
Labels: bug, documentation

#701 Add uv.lock for persistent env
  uv.lock
Labels: enhancement
