Repository NVIDIA/cloudai, pull requests merged in 2025-07, with the labels that each got.

#594 Remove default_cmd_args field from TestTemplateStrategy
  src/cloudai/_core/test_template_strategy.py
  src/cloudai/systems/lsf/lsf_command_gen_strategy.py
  src/cloudai/systems/slurm/slurm_command_gen_strategy.py
  src/cloudai/test_parser.py
  src/cloudai/workloads/jax_toolbox/slurm_command_gen_strategy.py
  src/cloudai/workloads/nccl_test/kubernetes_json_gen_strategy.py
  src/cloudai/workloads/nemo_launcher/slurm_command_gen_strategy.py
  src/cloudai/workloads/nixl_bench/slurm_command_gen_strategy.py
  src/cloudai/workloads/triton_inference/slurm_command_gen_strategy.py
  tests/json_gen_strategy/test_nccl_runai_json_gen_strategy.py
  tests/slurm_command_gen_strategy/test_bash_cmd_slurm_command_gen_strategy.py
  tests/slurm_command_gen_strategy/test_chakra_replay_slurm_command_gen_strategy.py
  tests/slurm_command_gen_strategy/test_common_slurm_command_gen_strategy.py
  tests/slurm_command_gen_strategy/test_jax_toolbox_slurm_command_gen_strategy.py
  tests/slurm_command_gen_strategy/test_nccl_slurm_command_gen_strategy.py
  tests/slurm_command_gen_strategy/test_nemo_launcher_slurm_command_gen_strategy.py
  tests/slurm_command_gen_strategy/test_nemo_run_slurm_command_gen_strategy.py
  tests/slurm_command_gen_strategy/test_nixl_bench_slurm_command_gen_strategy.py
  tests/slurm_command_gen_strategy/test_sleep_slurm_command_gen_strategy.py
  tests/slurm_command_gen_strategy/test_slurm_container_slurm_command_gen_strategy.py
  tests/slurm_command_gen_strategy/test_triton_inference_slurm_command_gen_strategy.py
  tests/slurm_command_gen_strategy/test_ucc_slurm_command_gen_strategy.py
  tests/test_acceptance.py
  tests/test_get_job_id.py
  tests/test_single_sbatch_runner.py
  tests/test_slurm_system.py
Labels: enhancement

#579 Enable NCCL w/ K8S SPCx
  src/cloudai/systems/kubernetes/kubernetes_system.py
  src/cloudai/workloads/nccl_test/kubernetes_json_gen_strategy.py
  tests/conftest.py
  tests/json_gen_strategy/test_nccl_kubernetes_json_gen_strategy.py
Labels: feature

#591 Handles comma in env vars values for NemoLauncher
  src/cloudai/workloads/nemo_launcher/slurm_command_gen_strategy.py
  tests/slurm_command_gen_strategy/test_nemo_launcher_slurm_command_gen_strategy.py
Labels: bug, enhancement

#599 Small improvements
  src/cloudai/_core/registry.py
  src/cloudai/registration.py
  src/cloudai/systems/slurm/slurm_system.py
  src/cloudai/test_parser.py
  src/cloudai/workloads/sleep/__init__.py
  src/cloudai/workloads/sleep/report_generation_strategy.py
  tests/test_registry.py
  tests/test_test_scenario.py
Labels: enhancement

#595 Update AI Dynamo config to use vLLM_V1 API.
  doc/ai_dynamo.md
  src/cloudai/workloads/ai_dynamo/__init__.py
  src/cloudai/workloads/ai_dynamo/ai_dynamo.py
  src/cloudai/workloads/ai_dynamo/report_generation_strategy.py
  src/cloudai/workloads/ai_dynamo/slurm_command_gen_strategy.py
  tests/ref_data/ai-dynamo.sbatch
  tests/report_generation_strategy/test_ai_dynamo_report_generation_strategy.py
  tests/slurm_command_gen_strategy/test_ai_dynamo_slurm_command_gen_strategy.py
  tests/test_acceptance.py
Labels: enhancement

#606 Docker cache fix
  src/cloudai/_core/installables.py
  src/cloudai/systems/slurm/docker_image_cache_manager.py
  tests/test_base_installer.py
  tests/test_docker_image_cache_manager.py
Labels: bug, enhancement

#593 Support for fp8 Llama3_405b
  src/cloudai/workloads/nemo_run/cloudai_nemorun.py
Labels: enhancement

#612 Support custom matgen args and set valid ppn
  src/cloudai/workloads/nixl_perftest/__init__.py
  src/cloudai/workloads/nixl_perftest/nixl_perftest.py
  src/cloudai/workloads/nixl_perftest/slurm_command_gen_strategy.py
  tests/slurm_command_gen_strategy/test_nixl_perftest_slurm_command_gen_strategy.py
Labels: bug
