Repository NVIDIA/cloudai, pull requests merged in 2025-04, with the labels that each got.

#433 Fix metadata collection
  src/cloudai/systems/slurm/strategy/slurm_command_gen_strategy.py
  tests/ref_data/gpt-no-hook.sbatch
  tests/ref_data/gpt-pre-test.sbatch
  tests/ref_data/grok-no-hook.sbatch
  tests/ref_data/grok-pre-test.sbatch
  tests/ref_data/megatron-run.sbatch
  tests/ref_data/nccl.sbatch
  tests/ref_data/nemo-run-no-hook.sbatch
  tests/ref_data/nemo-run-pre-test.sbatch
  tests/ref_data/sleep.sbatch
  tests/ref_data/slurm_container.sbatch
  tests/ref_data/ucc.sbatch
Labels: bug

#428 Add metrics support for UCC reporting
  src/cloudai/workloads/ucc_test/report_generation_strategy.py
  tests/report_generation_strategy/test_ucc_report_generation_strategy.py
Labels: enhancement

#431 Scenario reporter for DSE jobs
  src/cloudai/_core/base_runner.py
  src/cloudai/_core/configurator/cloudai_gym.py
  src/cloudai/_core/reporter.py
  src/cloudai/_core/runner.py
  src/cloudai/cli/handlers.py
  src/cloudai/runner/lsf/lsf_runner.py
  src/cloudai/runner/slurm/slurm_runner.py
  src/cloudai/runner/standalone/standalone_runner.py
  tests/test_job_submission_error.py
  tests/test_reporter.py
Labels: enhancement

#437 Fix installation check for File
  src/cloudai/installer/slurm_installer.py
  tests/test_slurm_installer.py
Labels: bug

#440 Fix unknown state of the group nodes
  src/cloudai/systems/slurm/slurm_system.py
Labels: bug

#444 Nemo Dry-Run/Run Fix
  src/cloudai/workloads/nemo_run/report_generation_strategy.py
  tests/report_generation_strategy/test_nemo_run_report_generation_strategy.py
Labels: bug

#446 Make sure error is printed for DSE + unknown metric
  src/cloudai/_core/test_scenario_parser.py
  tests/test_test_scenario.py
Labels: bug

#453 Replace pyright ignores with explicit type handling
  src/cloudai/workloads/jax_toolbox/slurm_command_gen_strategy.py
  src/cloudai/workloads/nccl_test/kubernetes_json_gen_strategy.py
  src/cloudai/workloads/nccl_test/slurm_command_gen_strategy.py
Labels: bug, enhancement

#449 Return None when main test has no time limit in calculate_total_time_limit
  src/cloudai/_core/test_scenario_parser.py
  tests/test_test_scenario_parser.py
Labels: bug

#450 Move Slurm-specific methods to SlurmCommandGenStrategy
  src/cloudai/_core/command_gen_strategy.py
  src/cloudai/_core/test_template.py
  src/cloudai/systems/slurm/strategy/slurm_command_gen_strategy.py
  tests/test_acceptance.py
Labels: bug, enhancement

#454 Move Slurm-specific methods to SlurmCommandGenStrategy
  src/cloudai/_core/test_template.py
  src/cloudai/systems/slurm/strategy/slurm_command_gen_strategy.py
  tests/slurm_command_gen_strategy/test_common_slurm_command_gen_strategy.py
Labels: enhancement

#456 Bug fix in src/cloudai/cli/handlers.py
  src/cloudai/cli/handlers.py
Labels: bug

#458 Support NCCL_TOPO_FILE in all SlurmCommandGenStrategy classes
  src/cloudai/systems/slurm/strategy/slurm_command_gen_strategy.py
  src/cloudai/workloads/nccl_test/slurm_command_gen_strategy.py
  tests/slurm_command_gen_strategy/test_common_slurm_command_gen_strategy.py
Labels: enhancement

#461 Fix: Include CANCELLED+ state in completed job status check
  src/cloudai/systems/slurm/slurm_system.py
Labels: bug

#467 Fix is_running for slurm
  .github/workflows/ci.yml
  conf/common/test_scenario/sleep.toml
  src/cloudai/_core/base_runner.py
  src/cloudai/systems/slurm/slurm_system.py
  tests/test_slurm_system.py
Labels: bug

#462 [Feature Request/Bug]: Remove Workspace Mount
  src/cloudai/workloads/nemo_run/slurm_command_gen_strategy.py
  tests/ref_data/nemo-run-no-hook.sbatch
  tests/ref_data/nemo-run-pre-test.sbatch
  tests/slurm_command_gen_strategy/test_nemo_run_slurm_command_gen_strategy.py
Labels: bug, feature

#470 Restore dry-run on system without slurm
  .github/workflows/ci.yml
  src/cloudai/_core/base_runner.py
Labels: enhancement

#471 Refactor: Use test definition's cmd_args for UCC command generation
  src/cloudai/workloads/ucc_test/slurm_command_gen_strategy.py
  tests/slurm_command_gen_strategy/test_ucc_slurm_command_gen_strategy.py
Labels: enhancement

#475 Updates and fixes for metadata collection
  src/cloudai/systems/slurm/slurm-metadata.sh
  src/cloudai/systems/slurm/strategy/slurm_command_gen_strategy.py
  tests/ref_data/sleep.sbatch
Labels: bug

#469 Integrate refactored Chakra replay
  src/cloudai/workloads/chakra_replay/chakra_replay.py
  src/cloudai/workloads/chakra_replay/report_generation_strategy.py
  src/cloudai/workloads/chakra_replay/slurm_command_gen_strategy.py
  tests/slurm_command_gen_strategy/test_chakra_replay_slurm_command_gen_strategy.py
  tests/test_test_definitions.py
Labels: enhancement

#478 Refactor: Use test definition's cmd_args for sleep command generation
  src/cloudai/workloads/sleep/kubernetes_json_gen_strategy.py
  src/cloudai/workloads/sleep/lsf_command_gen_strategy.py
  src/cloudai/workloads/sleep/standalone_command_gen_strategy.py
Labels: enhancement

#473 Update output path for DSE runs
  src/cloudai/_core/configurator/cloudai_gym.py
  src/cloudai/cli/handlers.py
  src/cloudai/workloads/nemo_run/report_generation_strategy.py
  tests/conftest.py
  tests/test_cloudaigym.py
Labels: bug, enhancement

#479 Collect more metadata for slurm jobs
  src/cloudai/runner/slurm/slurm_runner.py
  src/cloudai/systems/slurm/metadata.py
  src/cloudai/systems/slurm/slurm-metadata.sh
  src/cloudai/systems/slurm/slurm_system.py
  tests/test_slurm_system.py
Labels: enhancement

#480 Set sequence length explicitly in NeMoRun config and data model
  conf/common/test/nemo_run_llama3_8b.toml
  conf/common/test/nemo_run_llama3_8b_lora.toml
  src/cloudai/workloads/nemo_run/nemo_run.py
  tests/ref_data/nemo-run-no-hook.sbatch
  tests/ref_data/nemo-run-pre-test.sbatch
  tests/ref_data/nemo-run-vboost.sbatch
  tests/test_cloudaigym.py
Labels: enhancement

#481 Fix typo in src/cloudai/workloads/nemo_run/slurm_command_gen_strategy.py
  src/cloudai/workloads/nemo_run/slurm_command_gen_strategy.py
Labels: documentation, enhancement

#483 Validate save/load paths for MegatronRun
  src/cloudai/_core/exceptions.py
  src/cloudai/workloads/megatron_run/megatron_run.py
  tests/ref_data/megatron-run.sbatch
  tests/test_acceptance.py
  tests/test_test_definitions.py
Labels: enhancement

#486 Nemo2.0 fixes for Llama70b
  src/cloudai/workloads/nemo_run/cloudai_nemorun.py
Labels: enhancement

#488 Updates for slurm metadata
  src/cloudai/systems/slurm/metadata.py
  src/cloudai/systems/slurm/slurm-metadata.sh
Labels: bug, enhancement

#484 Clean up Nemo2.0 Configs
  conf/common/test/dse_nemo_run_llama3_8b.toml
  conf/common/test/dse_nemo_run_llama3_8b_fp8.toml
  conf/common/test/dse_nemo_run_llama_70b_fp8.toml
  conf/common/test/dse_nemo_run_nemotron_15b.toml
  conf/common/test/dse_nemo_run_nemotron_15b_fp8.toml
  conf/common/test/nemo_run_llama3_8b.toml
  conf/common/test/nemo_run_llama3_8b_lora.toml
  conf/common/test_scenario/dse_nemo_run_llama3_8b.toml
  conf/common/test_scenario/nemo_run_llama3_8b_lora.toml
  conf/experimental/test/nemo_run_nemotron_15b_bf16_128_node.toml
  conf/experimental/test/nemo_run_nemotron_15b_bf16_16_node.toml
  conf/experimental/test/nemo_run_nemotron_15b_bf16_256_node.toml
  conf/experimental/test/nemo_run_nemotron_15b_bf16_2_node.toml
  conf/experimental/test/nemo_run_nemotron_15b_bf16_32_node.toml
  conf/experimental/test/nemo_run_nemotron_15b_bf16_4_node.toml
  conf/experimental/test/nemo_run_nemotron_15b_bf16_64_node.toml
  conf/experimental/test/nemo_run_nemotron_15b_bf16_8_node.toml
  conf/experimental/test/nemo_run_nemotron_15b_fp8_128_node.toml
  conf/experimental/test/nemo_run_nemotron_15b_fp8_16_node.toml
  conf/experimental/test/nemo_run_nemotron_15b_fp8_256_node.toml
  conf/experimental/test/nemo_run_nemotron_15b_fp8_2_node.toml
  conf/experimental/test/nemo_run_nemotron_15b_fp8_32_node.toml
  conf/experimental/test/nemo_run_nemotron_15b_fp8_4_node.toml
  conf/experimental/test/nemo_run_nemotron_15b_fp8_64_node.toml
  conf/experimental/test/nemo_run_nemotron_15b_fp8_8_node.toml
  conf/experimental/test_scenario/nemo_run_nemotron15b_bf16.toml
  conf/experimental/test_scenario/nemo_run_nemotron15b_fp8.toml
Labels: enhancement

#485 Add context manager to ensure kube config exists
  src/cloudai/cli/handlers.py
Labels: bug

#464 Support data repository for NeMoRun LLAMA models
  .gitignore
  USER_GUIDE.md
  conf/common/system/example_slurm_cluster.toml
  src/cloudai/__init__.py
  src/cloudai/systems/slurm/slurm_system.py
  src/cloudai/workloads/nemo_run/__init__.py
  src/cloudai/workloads/nemo_run/data_store_report_generation_strategy.py
  src/cloudai/workloads/nemo_run/http_data_repository.py
  src/cloudai/workloads/nemo_run/nemo_run.py
  tests/report_generation_strategy/test_data_store_report_generation_strategy.py
  tests/test_test_scenario.py
Labels: feature

#460 Add TarballReporter for archiving test results on failure
  src/cloudai/__init__.py
  src/cloudai/_core/reporter.py
  tests/test_init.py
Labels: feature

#491 Fix tarball name to preserve full directory name with dots intact
  src/cloudai/_core/reporter.py
  tests/test_reporter.py
Labels: bug

#494 Prevent NeMoRunDataStoreReportGenerationStrategy from overriding metric logic
  src/cloudai/workloads/nemo_run/data_store_report_generation_strategy.py
Labels: bug

#499 Add Bokeh report generation to NeMoRunReportGenerationStrategy class
  src/cloudai/workloads/nemo_run/report_generation_strategy.py
Labels: enhancement

#493 Fix premature runner exit by looping until all jobs are complete
  src/cloudai/_core/base_runner.py
Labels: bug

#496 Nemo2.0 Perf Features (next set)
  conf/common/test/dse_nemo_run_llama3_8b_fp8.toml
  src/cloudai/systems/slurm/strategy/slurm_command_gen_strategy.py
  src/cloudai/workloads/nemo_run/cloudai_nemorun.py
  src/cloudai/workloads/nemo_run/nemo_run.py
  src/cloudai/workloads/nemo_run/slurm_command_gen_strategy.py
  tests/ref_data/nemo-run-no-hook.sbatch
  tests/ref_data/nemo-run-pre-test.sbatch
  tests/ref_data/nemo-run-vboost.sbatch
Labels: enhancement

#505 Remove requirements files to rely on pyproject for dependencies
  .github/workflows/ci.yml
  README.md
  pyproject.toml
  requirements-dev.txt
  requirements.txt
  tests/test_package.py
Labels: enhancement

#504 Revert `Integrate refactored Chakra replay #469`
  src/cloudai/workloads/chakra_replay/chakra_replay.py
  src/cloudai/workloads/chakra_replay/report_generation_strategy.py
  src/cloudai/workloads/chakra_replay/slurm_command_gen_strategy.py
  tests/slurm_command_gen_strategy/test_chakra_replay_slurm_command_gen_strategy.py
  tests/test_test_definitions.py
Labels: feature
