Repository NVIDIA/cloudai, pull requests merged in 2025-06, with the labels that each got.

#532 Add LLAMA3 8b to NeMo acceptance
  conf/release/nemo_acceptance/test/nemo_run_llama3_8b.toml
  conf/release/nemo_acceptance/test_scenario/nemo_run_llama3_8b.toml
Labels: enhancement

#551 Allow val_check_interval to be int, float, or list of both
  src/cloudai/workloads/nemo_run/nemo_run.py
Labels: bug

#548 Make sure mark_as_installed respects system config
  src/cloudai/_core/base_installer.py
  src/cloudai/installer/slurm_installer.py
  tests/test_base_installer.py
  tests/test_slurm_installer.py
Labels: bug

#487 Allow sweeps for number of nodes
  src/cloudai/_core/configurator/cloudai_gym.py
  src/cloudai/_core/reporter.py
  src/cloudai/_core/test_scenario.py
  src/cloudai/_core/test_scenario_parser.py
  src/cloudai/cli/handlers.py
  src/cloudai/models/scenario.py
  src/cloudai/models/workload.py
  src/cloudai/systems/slurm/strategy/slurm_command_gen_strategy.py
  src/cloudai/workloads/jax_toolbox/slurm_command_gen_strategy.py
  src/cloudai/workloads/nccl_test/kubernetes_json_gen_strategy.py
  src/cloudai/workloads/nemo_launcher/slurm_command_gen_strategy.py
  src/cloudai/workloads/nemo_run/nemo_run.py
  src/cloudai/workloads/nemo_run/slurm_command_gen_strategy.py
  src/cloudai/workloads/triton_inference/slurm_command_gen_strategy.py
  tests/slurm_command_gen_strategy/test_nemo_run_slurm_command_gen_strategy.py
  tests/test_cloudaigym.py
  tests/test_job_type_handler.py
  tests/test_reporter.py
  tests/test_test_scenario.py
Labels: feature

#556 Refactor supports_gpu_directives to focus on GresTypes
  src/cloudai/systems/slurm/slurm_system.py
  tests/test_slurm_system.py
Labels: bug

#555 Add single sbatch runner for slurm systems
  USER_GUIDE.md
  src/cloudai/_core/test_scenario_parser.py
  src/cloudai/cli/cli.py
  src/cloudai/cli/handlers.py
  src/cloudai/runner/slurm/single_sbatch_runner.py
  src/cloudai/util/__init__.py
  src/cloudai/util/utils.py
  tests/test_acceptance.py
  tests/test_cli.py
  tests/test_registry.py
  tests/test_single_sbatch_runner.py
Labels: feature

#560 Fix DeepSeekR1 inference report
  src/cloudai/workloads/triton_inference/report_generation_strategy.py
Labels: bug, enhancement

#563 Generate reports for DSE jobs
  src/cloudai/cli/handlers.py
Labels: bug

#565 Do not use --copies for venv creation
  src/cloudai/systems/slurm/slurm_installer.py
  tests/test_slurm_installer.py
Labels: bug

#567 Expand slurm meta to have per-step information
  src/cloudai/cli/handlers.py
  src/cloudai/systems/slurm/__init__.py
  src/cloudai/systems/slurm/single_sbatch_runner.py
  src/cloudai/systems/slurm/slurm_metadata.py
  src/cloudai/systems/slurm/slurm_runner.py
  src/cloudai/systems/slurm/slurm_system.py
  tests/conftest.py
  tests/test_single_sbatch_runner.py
  tests/test_slurm_system.py
Labels: enhancement

#568 Remove JAX configs as used image is not available
  conf/common/test/dse_jaxtoolbox_grok.toml
  conf/common/test_scenario/dse_jaxtoolbox.toml
Labels: bug, enhancement

#573 Fix for handling srun with multiline commands
  src/cloudai/systems/slurm/slurm_metadata.py
  src/cloudai/systems/slurm/slurm_system.py
  tests/test_slurm_system.py
Labels: bug

#570 Add BashCmd workload
  src/cloudai/workloads/bash_cmd/__init__.py
  src/cloudai/workloads/bash_cmd/bash_cmd.py
  tests/slurm_command_gen_strategy/test_bash_cmd_slurm_command_gen_strategy.py
Labels: feature

#574 Correctly load and save tdef as part of TestRunDetails
  src/cloudai/models/scenario.py
  tests/test_reporter.py
  tests/test_test_definitions.py
Labels: enhancement

#575 Make NIXL work in single-sbatch mode
  src/cloudai/systems/slurm/single_sbatch_runner.py
  src/cloudai/workloads/nixl_bench/nixl_bench.py
  src/cloudai/workloads/nixl_bench/slurm_command_gen_strategy.py
  tests/ref_data/nixl_bench.sbatch
  tests/slurm_command_gen_strategy/test_nixl_bench_slurm_command_gen_strategy.py
  tests/test_acceptance.py
  tests/test_single_sbatch_runner.py
  tests/test_test_definitions.py
Labels: enhancement

#577 Re-work slurm node status update
  src/cloudai/systems/slurm/slurm_node.py
  src/cloudai/systems/slurm/slurm_system.py
  tests/test_slurm_allocation.py
  tests/test_slurm_system.py
Labels: bug, enhancement

#576 Add NIXL summary report
  pyproject.toml
  src/cloudai/registration.py
  src/cloudai/util/lazy_imports.py
  src/cloudai/util/nixl_report_template.jinja2
  src/cloudai/workloads/nixl_bench/__init__.py
  src/cloudai/workloads/nixl_bench/nixl_summary_report.py
  tests/test_init.py
Labels: enhancement

#578 Update regex to correctly extract full GPU type names including suffixes and variants
  src/cloudai/workloads/nccl_test/performance_report_generation_strategy.py
  tests/report_generation_strategy/test_nccl_performance_report_generation_strategy.py
Labels: bug

#581 Align method with BaseRunner by renaming to on_job_completion and removing async
  src/cloudai/systems/kubernetes/kubernetes_runner.py
Labels: bug

#583 Add DockerImage support to Kubernetes installer methods
  src/cloudai/systems/kubernetes/kubernetes_installer.py
Labels: bug, enhancement

#585 Match json_gen_strategy implementation to command_gen_strategy
  src/cloudai/_core/test_template.py
Labels: enhancement

#587 Silently skip NIXL summary generation if no NIXL tests
  src/cloudai/workloads/nixl_bench/nixl_summary_report.py
Labels: enhancement

#582 Llama31_405b
  src/cloudai/workloads/nemo_run/cloudai_nemorun.py
  src/cloudai/workloads/nemo_run/nemo_run.py
  src/cloudai/workloads/nemo_run/slurm_command_gen_strategy.py
Labels: feature

#590 Update UCC configs
  conf/common/test/ucc_test.toml
  conf/common/test/ucc_test_allgather.toml
  conf/common/test/ucc_test_allreduce.toml
  conf/common/test/ucc_test_alltoall.toml
  conf/common/test_scenario/ucc_test.toml
  src/cloudai/workloads/ucc_test/ucc.py
  tests/report_generation_strategy/test_ucc_report_generation_strategy.py
  tests/slurm_command_gen_strategy/test_ucc_slurm_command_gen_strategy.py
  tests/test_acceptance.py
  tests/test_test_definitions.py
Labels: enhancement

#592 Avoid confusing post_test/pre_test folder structure
  src/cloudai/systems/slurm/slurm_command_gen_strategy.py
Labels: bug
