Repository NVIDIA/cloudai, pull requests merged in 2025-05, with the labels that each got.

#508 Bump version to v1.3
  .github/workflows/ci.yml
  .python-version
  pyproject.toml
  src/cloudai/_core/base_runner.py
  src/cloudai/_core/configurator/grid_search.py
  src/cloudai/_core/test_parser.py
  src/cloudai/systems/kubernetes/kubernetes_system.py
  src/cloudai/systems/lsf/lsf_node.py
  src/cloudai/systems/slurm/slurm_node.py
  src/cloudai/workloads/jax_toolbox/jax_toolbox.py
  src/cloudai/workloads/jax_toolbox/slurm_command_gen_strategy.py
  src/cloudai/workloads/megatron_run/megatron_run.py
  tests/ref_data/gpt.run
  tests/report_generation_strategy/test_data_store_report_generation_strategy.py
  tests/test_check_copyright_headers.py
  tests/test_slurm_system.py
Labels: enhancement

#509 Support hostfile generation and override distribution for explicit nodes
  USER_GUIDE.md
  src/cloudai/systems/slurm/strategy/slurm_command_gen_strategy.py
  tests/ref_data/gpt-no-hook.sbatch
  tests/ref_data/gpt-pre-test.sbatch
  tests/ref_data/grok-no-hook.sbatch
  tests/ref_data/grok-pre-test.sbatch
  tests/ref_data/megatron-run.sbatch
  tests/ref_data/nccl.sbatch
  tests/ref_data/nemo-run-no-hook.sbatch
  tests/ref_data/nemo-run-pre-test.sbatch
  tests/ref_data/nemo-run-vboost.sbatch
  tests/ref_data/sleep.sbatch
  tests/ref_data/slurm_container.sbatch
  tests/ref_data/ucc.sbatch
  tests/slurm_command_gen_strategy/test_common_slurm_command_gen_strategy.py
Labels: feature

#512 Handle missing credentials when creating HttpDataRepository
  src/cloudai/workloads/nemo_run/data_store_report_generation_strategy.py
  src/cloudai/workloads/nemo_run/http_data_repository.py
Labels: bug

#514 Correctly handle values with spaces for env vars
  src/cloudai/workloads/nemo_launcher/slurm_command_gen_strategy.py
  tests/ref_data/nemo-launcher.sbatch
  tests/slurm_command_gen_strategy/test_nemo_launcher_slurm_command_gen_strategy.py
  tests/test_acceptance.py
Labels: bug

#501 Change Scenario Report Map type from Set to List
  src/cloudai/_core/registry.py
  tests/test_registry.py
Labels: enhancement

#515 Verify if input path exist on argparse level
  src/cloudai/cli/cli.py
  tests/test_cli.py
Labels: enhancement

#517 Apply style to scenario report
  src/cloudai/_core/reporter.py
  src/cloudai/util/base-report.jinja2
  src/cloudai/util/general-report.jinja2
  src/cloudai/util/general-slurm-report.jinja2
Labels: enhancement

#393 Control workload settings from scenario
  conf/common/test_scenario/nccl_tests_inline.toml
  conf/experimental/test/nemo_launcher_nemotron_15b_bf16_16_node.toml
  conf/experimental/test/nemo_launcher_nemotron_15b_bf16_32_node.toml
  conf/experimental/test/nemo_launcher_nemotron_15b_bf16_4_node.toml
  conf/experimental/test/nemo_launcher_nemotron_15b_bf16_64_node.toml
  conf/experimental/test/nemo_launcher_nemotron_15b_bf16_8_node.toml
  conf/experimental/test_scenario/nemo_launcher_nemotron_15b_bf16.toml
  conf/experimental/test_scenario/nemo_launcher_nemotron_15b_bf16_16_node.toml
  conf/experimental/test_scenario/nemo_launcher_nemotron_15b_bf16_32_node.toml
  conf/experimental/test_scenario/nemo_launcher_nemotron_15b_bf16_4_node.toml
  conf/experimental/test_scenario/nemo_launcher_nemotron_15b_bf16_64_node.toml
  conf/experimental/test_scenario/nemo_launcher_nemotron_15b_bf16_8_node.toml
  src/cloudai/__init__.py
  src/cloudai/_core/registry.py
  src/cloudai/_core/test.py
  src/cloudai/_core/test_parser.py
  src/cloudai/_core/test_scenario_parser.py
  src/cloudai/_core/test_template.py
  src/cloudai/cli/cli.py
  src/cloudai/cli/handlers.py
  src/cloudai/models/scenario.py
  src/cloudai/models/workload.py
  src/cloudai/parser.py
  src/cloudai/workloads/jax_toolbox/jax_toolbox.py
  src/cloudai/workloads/megatron_run/megatron_run.py
  src/cloudai/workloads/nccl_test/nccl.py
  src/cloudai/workloads/nemo_launcher/nemo_launcher.py
  src/cloudai/workloads/nemo_run/nemo_run.py
  src/cloudai/workloads/sleep/sleep.py
  src/cloudai/workloads/slurm_container/slurm_container.py
  src/cloudai/workloads/ucc_test/ucc.py
  tests/conftest.py
  tests/report_generation_strategy/test_ucc_report_generation_strategy.py
  tests/slurm_command_gen_strategy/test_common_slurm_command_gen_strategy.py
  tests/slurm_command_gen_strategy/test_jax_toolbox_slurm_command_gen_strategy.py
  tests/slurm_command_gen_strategy/test_slurm_container_slurm_command_gen_strategy.py
  tests/test_acceptance.py
  tests/test_registry.py
  tests/test_reporter.py
  tests/test_test_definitions.py
  tests/test_test_scenario.py
  tests/test_toml_files.py
Labels: feature

#518 Make installabes() non-abstract
  tests/conftest.py
  tests/report_generation_strategy/test_nccl_prediction_report_generator.py
  tests/test_registry.py
  tests/test_test_definitions.py
  tests/test_test_scenario.py
  tests/test_test_scenario_parser.py
Labels: enhancement

#503 Add DeepSeek-R1 Inference
  USER_GUIDE.md
  src/cloudai/__init__.py
  src/cloudai/workloads/triton_inference/__init__.py
  src/cloudai/workloads/triton_inference/report_generation_strategy.py
  src/cloudai/workloads/triton_inference/slurm_command_gen_strategy.py
  src/cloudai/workloads/triton_inference/triton_inference.py
  tests/ref_data/triton-inference-start_server_wrapper.sh
  tests/ref_data/triton-inference.sbatch
  tests/slurm_command_gen_strategy/test_triton_inference_slurm_command_gen_strategy.py
  tests/test_acceptance.py
  tests/test_init.py
  tests/test_test_scenario.py
Labels: feature

#490 Add NeMoRunJobStatusRetrievalStrategy and register it in the strategy registry
  src/cloudai/__init__.py
  src/cloudai/workloads/nemo_run/__init__.py
  src/cloudai/workloads/nemo_run/job_status_retrieval_strategy.py
  tests/job_status_retrieval_strategy/test_nemo_run_job_status_retrieval_strategy.py
  tests/test_init.py
Labels: enhancement

#521 Update MegatronRun model dump logic
  src/cloudai/workloads/megatron_run/megatron_run.py
  tests/test_test_definitions.py
  tests/test_test_scenario.py
Labels: bug

#523 Updated README
  README.md
Labels: documentation

#525 Fix how test-in-scenario is merge with test-in-toml
  src/cloudai/_core/test_scenario_parser.py
  src/cloudai/models/scenario.py
  tests/test_test_scenario.py
Labels: bug

#527 Remove venv folder if requirements installation failed
  src/cloudai/installer/slurm_installer.py
  tests/test_slurm_installer.py
Labels: bug, enhancement

#513 Move sweeps logic to TestRun
  src/cloudai/_core/configurator/cloudai_gym.py
  src/cloudai/_core/test_scenario.py
  src/cloudai/_core/test_template_strategy.py
  tests/test_cloudaigym.py
Labels: enhancement

#535 Optimize slurm updates
  src/cloudai/parser.py
  src/cloudai/systems/slurm/slurm_system.py
  src/cloudai/systems/slurm/strategy/slurm_command_gen_strategy.py
  tests/test_slurm_system.py
Labels: bug, enhancement

#531 Add extra_srun_args & scripts in SlurmContainerTestDef
  src/cloudai/workloads/slurm_container/slurm_command_gen_strategy.py
  src/cloudai/workloads/slurm_container/slurm_container.py
  tests/slurm_command_gen_strategy/test_slurm_container_slurm_command_gen_strategy.py
  tests/test_test_definitions.py
Labels: enhancement, feature

#537 Dump CloudAI version into generated sbatch script
  src/cloudai/systems/slurm/strategy/slurm_command_gen_strategy.py
  tests/ref_data/gpt-no-hook.sbatch
  tests/ref_data/gpt-pre-test.sbatch
  tests/ref_data/grok-no-hook.sbatch
  tests/ref_data/grok-pre-test.sbatch
  tests/ref_data/megatron-run.sbatch
  tests/ref_data/nccl.sbatch
  tests/ref_data/nemo-run-no-hook.sbatch
  tests/ref_data/nemo-run-pre-test.sbatch
  tests/ref_data/nemo-run-vboost.sbatch
  tests/ref_data/sleep.sbatch
  tests/ref_data/slurm_container.sbatch
  tests/ref_data/triton-inference.sbatch
  tests/ref_data/ucc.sbatch
  tests/test_acceptance.py
Labels: enhancement

#530 Remove venv folder if requirements installation failed
  src/cloudai/installer/slurm_installer.py
  tests/test_slurm_installer.py
Labels: bug, enhancement

#538 Reduce usage of slurm_args
  src/cloudai/systems/slurm/strategy/slurm_command_gen_strategy.py
  src/cloudai/workloads/chakra_replay/slurm_command_gen_strategy.py
  src/cloudai/workloads/jax_toolbox/slurm_command_gen_strategy.py
  src/cloudai/workloads/megatron_run/slurm_command_gen_strategy.py
  src/cloudai/workloads/nccl_test/slurm_command_gen_strategy.py
  src/cloudai/workloads/nemo_run/slurm_command_gen_strategy.py
  src/cloudai/workloads/triton_inference/slurm_command_gen_strategy.py
  src/cloudai/workloads/ucc_test/slurm_command_gen_strategy.py
  tests/slurm_command_gen_strategy/test_chakra_replay_slurm_command_gen_strategy.py
  tests/slurm_command_gen_strategy/test_common_slurm_command_gen_strategy.py
  tests/test_slurm_system.py
Labels: enhancement

#534 Address comments from #513
  src/cloudai/_core/test_scenario.py
  tests/test_cloudaigym.py
Labels: enhancement

#539 Get rid of _parse_slurm_args
  src/cloudai/systems/slurm/strategy/slurm_command_gen_strategy.py
  src/cloudai/workloads/chakra_replay/slurm_command_gen_strategy.py
  src/cloudai/workloads/jax_toolbox/slurm_command_gen_strategy.py
  src/cloudai/workloads/megatron_run/slurm_command_gen_strategy.py
  src/cloudai/workloads/nccl_test/slurm_command_gen_strategy.py
  src/cloudai/workloads/nemo_run/slurm_command_gen_strategy.py
  src/cloudai/workloads/slurm_container/slurm_command_gen_strategy.py
  src/cloudai/workloads/triton_inference/slurm_command_gen_strategy.py
  src/cloudai/workloads/ucc_test/slurm_command_gen_strategy.py
  tests/ref_data/gpt-no-hook.sbatch
  tests/ref_data/gpt-pre-test.sbatch
  tests/ref_data/grok-no-hook.sbatch
  tests/ref_data/grok-pre-test.sbatch
  tests/slurm_command_gen_strategy/test_chakra_replay_slurm_command_gen_strategy.py
  tests/slurm_command_gen_strategy/test_common_slurm_command_gen_strategy.py
  tests/slurm_command_gen_strategy/test_triton_inference_slurm_command_gen_strategy.py
Labels: enhancement

#544 Set srun job name to "<account>-CloudAI_install_docker_image.%Y%m%d_%H%M%S"
  src/cloudai/util/docker_image_cache_manager.py
  tests/test_docker_image_cache_manager.py
Labels: bug, enhancement

#536 Per-rank env vars evaluation
  src/cloudai/systems/slurm/strategy/slurm_command_gen_strategy.py
  src/cloudai/workloads/slurm_container/slurm_command_gen_strategy.py
  tests/conftest.py
  tests/ref_data/gpt-no-hook.sbatch
  tests/ref_data/gpt-pre-test.sbatch
  tests/ref_data/grok-no-hook.sbatch
  tests/ref_data/grok-pre-test.sbatch
  tests/ref_data/megatron-run.sbatch
  tests/ref_data/nccl.sbatch
  tests/ref_data/nemo-run-no-hook.sbatch
  tests/ref_data/nemo-run-pre-test.sbatch
  tests/ref_data/nemo-run-vboost.sbatch
  tests/ref_data/sleep.sbatch
  tests/ref_data/slurm_container.sbatch
  tests/ref_data/triton-inference.sbatch
  tests/ref_data/ucc.sbatch
  tests/slurm_command_gen_strategy/test_common_slurm_command_gen_strategy.py
  tests/slurm_command_gen_strategy/test_slurm_container_slurm_command_gen_strategy.py
Labels: enhancement

#524 Store test details and best config for DSE
  src/cloudai/_core/base_runner.py
  src/cloudai/_core/command_gen_strategy.py
  src/cloudai/_core/reporter.py
  src/cloudai/_core/test_template.py
  src/cloudai/models/scenario.py
  src/cloudai/runner/slurm/slurm_runner.py
  src/cloudai/systems/slurm/strategy/slurm_command_gen_strategy.py
  tests/test_acceptance.py
  tests/test_reporter.py
Labels: feature

#546 Use copies for venv creation + fix tests
  src/cloudai/installer/slurm_installer.py
  tests/ref_data/nixl_bench.sbatch
  tests/test_slurm_installer.py
Labels: bug, enhancement
