Repository NVIDIA/cloudai, pull requests merged in 2025-02, with the labels that each got.

#355 Always mount current output dir as /cloudai_run_results
  USER_GUIDE.md
  src/cloudai/schema/test_template/chakra_replay/slurm_command_gen_strategy.py
  src/cloudai/schema/test_template/jax_toolbox/slurm_command_gen_strategy.py
  src/cloudai/schema/test_template/nccl_test/slurm_command_gen_strategy.py
  src/cloudai/schema/test_template/nemo_launcher/slurm_command_gen_strategy.py
  src/cloudai/schema/test_template/nemo_run/slurm_command_gen_strategy.py
  src/cloudai/schema/test_template/sleep/slurm_command_gen_strategy.py
  src/cloudai/schema/test_template/slurm_container/slurm_command_gen_strategy.py
  src/cloudai/schema/test_template/ucc_test/slurm_command_gen_strategy.py
  src/cloudai/systems/slurm/strategy/slurm_command_gen_strategy.py
  src/cloudai/test_definitions/slurm_container.py
  tests/ref_data/gpt-no-hook.sbatch
  tests/ref_data/gpt-pre-test.sbatch
  tests/ref_data/grok-no-hook.sbatch
  tests/ref_data/grok-pre-test.sbatch
  tests/ref_data/nccl.sbatch
  tests/ref_data/nemo-run-no-hook.sbatch
  tests/ref_data/nemo-run-pre-test.sbatch
  tests/ref_data/slurm_container.sbatch
  tests/ref_data/ucc.sbatch
  tests/slurm_command_gen_strategy/test_chakra_replay_slurm_command_gen_strategy.py
  tests/slurm_command_gen_strategy/test_common_slurm_command_gen_strategy.py
  tests/slurm_command_gen_strategy/test_nccl_slurm_command_gen_strategy.py
Labels: feature

#356 Support custom mounts for slurm container jobs
  USER_GUIDE.md
  src/cloudai/_core/test.py
  src/cloudai/systems/slurm/strategy/slurm_command_gen_strategy.py
  tests/slurm_command_gen_strategy/test_common_slurm_command_gen_strategy.py
Labels: enhancement, feature

#341 Manage fields' serialization of SlurmSystem
  src/cloudai/systems/slurm/slurm_system.py
  tests/test_slurm_system.py
Labels: enhancement

#358 Introduce configurable mounts for git repos
  src/cloudai/__init__.py
  src/cloudai/_core/base_installer.py
  src/cloudai/_core/installables.py
  src/cloudai/_core/test.py
  src/cloudai/installer/slurm_installer.py
  src/cloudai/schema/test_template/nemo_launcher/slurm_command_gen_strategy.py
  src/cloudai/schema/test_template/slurm_container/slurm_command_gen_strategy.py
  src/cloudai/systems/slurm/strategy/slurm_command_gen_strategy.py
  src/cloudai/test_definitions/chakra_replay.py
  src/cloudai/test_definitions/gpt.py
  src/cloudai/test_definitions/grok.py
  src/cloudai/test_definitions/nccl.py
  src/cloudai/test_definitions/nemo_launcher.py
  src/cloudai/test_definitions/nemo_run.py
  src/cloudai/test_definitions/nemotron.py
  src/cloudai/test_definitions/sleep.py
  src/cloudai/test_definitions/slurm_container.py
  src/cloudai/test_definitions/ucc.py
  tests/ref_data/slurm_container.sbatch
  tests/slurm_command_gen_strategy/test_common_slurm_command_gen_strategy.py
  tests/slurm_command_gen_strategy/test_nemo_launcher_slurm_command_gen_strategy.py
  tests/test_acceptance.py
  tests/test_base_installer.py
  tests/test_slurm_installer.py
Labels: enhancement

#363 Small housekeeping updates
  src/cloudai/cli/cli.py
  src/cloudai/cli/handlers.py
  src/cloudai/systems/slurm/slurm_system.py
  tests/test_cli.py
Labels: enhancement

#360 Rework reporting logic
  README.md
  pyproject.toml
  src/cloudai/__init__.py
  src/cloudai/_core/configurator/cloudai_gym.py
  src/cloudai/_core/report_generation_strategy.py
  src/cloudai/_core/reporter.py
  src/cloudai/_core/test_parser.py
  src/cloudai/_core/test_template.py
  src/cloudai/cli/handlers.py
  src/cloudai/report_generator/__init__.py
  src/cloudai/schema/test_template/chakra_replay/report_generation_strategy.py
  src/cloudai/schema/test_template/jax_toolbox/report_generation_strategy.py
  src/cloudai/schema/test_template/nccl_test/report_generation_strategy.py
  src/cloudai/schema/test_template/nemo_launcher/report_generation_strategy.py
  src/cloudai/schema/test_template/nemo_run/report_generation_strategy.py
  src/cloudai/schema/test_template/sleep/report_generation_strategy.py
  src/cloudai/schema/test_template/slurm_container/report_generation_strategy.py
  src/cloudai/schema/test_template/ucc_test/report_generation_strategy.py
  tests/report_generation_strategy/test_jax_toolbox_report_generation_strategy.py
  tests/report_generation_strategy/test_nccl_report_generation_strategy.py
  tests/report_generation_strategy/test_nemo_run_report_generation_strategy.py
Labels: enhancement, feature

#365 Llama and Nemotron Configs
  conf/common/test/dse_nemo_run_llama_70b_fp8.toml
  conf/common/test/dse_nemo_run_nemotron_15b.toml
  conf/common/test/dse_nemo_run_nemotron_15b_fp8.toml
Labels: enhancement

#370 Update NeMo dataset link in USER_GUIDE.md
  USER_GUIDE.md
Labels: documentation

#371 Add .github/CODEOWNERS
  .github/CODEOWNERS
Labels: feature

#372 Use custom script for NemoRun jobs
  conf/common/test/dse_nemo_run_nemotron_15b_fp8.toml
  pyproject.toml
  src/cloudai/__init__.py
  src/cloudai/_core/installables.py
  src/cloudai/installer/slurm_installer.py
  src/cloudai/workloads/nemo_run/cloudai_nemorun.py
  src/cloudai/workloads/nemo_run/nemo_run.py
  src/cloudai/workloads/nemo_run/slurm_command_gen_strategy.py
  tests/ref_data/nemo-run-no-hook.sbatch
  tests/ref_data/nemo-run-pre-test.sbatch
  tests/slurm_command_gen_strategy/test_nemo_run_slurm_command_gen_strategy.py
  tests/test_acceptance.py
  tests/test_slurm_installer.py
Labels: feature

#376 Allow uint8 in NCCL ALLtoALL
  src/cloudai/workloads/nccl_test/nccl.py
Labels: enhancement

#373 Allow unknown fields for cmd_args in test definitions
  .github/workflows/ci.yml
  src/cloudai/_core/test.py
  src/cloudai/_core/test_parser.py
  src/cloudai/cli/cli.py
  src/cloudai/cli/handlers.py
  src/cloudai/workloads/nemo_run/nemo_run.py
  tests/test_cli.py
  tests/test_cloudaigym.py
  tests/test_test_definitions.py
Labels: feature

#378 Remove unused code from SlurmSystem
  src/cloudai/systems/slurm/slurm_system.py
Labels: enhancement

#377 Add nemo_launcher_nemotron_15b configurations
  .github/workflows/ci.yml
  conf/experimental/test/nemo_launcher_nemotron_15b_bf16_128_node.toml
  conf/experimental/test/nemo_launcher_nemotron_15b_bf16_16_node.toml
  conf/experimental/test/nemo_launcher_nemotron_15b_bf16_256_node.toml
  conf/experimental/test/nemo_launcher_nemotron_15b_bf16_2_node.toml
  conf/experimental/test/nemo_launcher_nemotron_15b_bf16_32_node.toml
  conf/experimental/test/nemo_launcher_nemotron_15b_bf16_4_node.toml
  conf/experimental/test/nemo_launcher_nemotron_15b_bf16_64_node.toml
  conf/experimental/test/nemo_launcher_nemotron_15b_bf16_8_node.toml
  conf/experimental/test/nemo_launcher_nemotron_15b_fp8_128_node.toml
  conf/experimental/test/nemo_launcher_nemotron_15b_fp8_16_node.toml
  conf/experimental/test/nemo_launcher_nemotron_15b_fp8_256_node.toml
  conf/experimental/test/nemo_launcher_nemotron_15b_fp8_2_node.toml
  conf/experimental/test/nemo_launcher_nemotron_15b_fp8_32_node.toml
  conf/experimental/test/nemo_launcher_nemotron_15b_fp8_4_node.toml
  conf/experimental/test/nemo_launcher_nemotron_15b_fp8_64_node.toml
  conf/experimental/test/nemo_launcher_nemotron_15b_fp8_8_node.toml
  conf/experimental/test_scenario/nemo_launcher_nemotron_15b_bf16.toml
  conf/experimental/test_scenario/nemo_launcher_nemotron_15b_fp8.toml
  src/cloudai/workloads/nemo_launcher/nemo_launcher.py
  src/cloudai/workloads/nemo_launcher/slurm_command_gen_strategy.py
  tests/slurm_command_gen_strategy/test_nemo_launcher_slurm_command_gen_strategy.py
Labels: enhancement

#368 Create ranks mapping file for slurm jobs
  src/cloudai/systems/slurm/strategy/slurm_command_gen_strategy.py
  tests/ref_data/gpt-no-hook.sbatch
  tests/ref_data/gpt-pre-test.sbatch
  tests/ref_data/grok-no-hook.sbatch
  tests/ref_data/grok-pre-test.sbatch
  tests/ref_data/nccl.sbatch
  tests/ref_data/nemo-run-no-hook.sbatch
  tests/ref_data/nemo-run-pre-test.sbatch
  tests/ref_data/sleep.sbatch
  tests/ref_data/slurm_container.sbatch
  tests/ref_data/ucc.sbatch
  tests/slurm_command_gen_strategy/test_common_slurm_command_gen_strategy.py
Labels: enhancement, feature

#380 Nemotron15b (fp8/bf16) for Acceptance (Nemo2.0)
  conf/experimental/test/nemo_run_nemotron_15b_bf16_128_node.toml
  conf/experimental/test/nemo_run_nemotron_15b_bf16_16_node.toml
  conf/experimental/test/nemo_run_nemotron_15b_bf16_256_node.toml
  conf/experimental/test/nemo_run_nemotron_15b_bf16_2_node.toml
  conf/experimental/test/nemo_run_nemotron_15b_bf16_32_node.toml
  conf/experimental/test/nemo_run_nemotron_15b_bf16_4_node.toml
  conf/experimental/test/nemo_run_nemotron_15b_bf16_64_node.toml
  conf/experimental/test/nemo_run_nemotron_15b_bf16_8_node.toml
  conf/experimental/test/nemo_run_nemotron_15b_fp8_128_node.toml
  conf/experimental/test/nemo_run_nemotron_15b_fp8_16_node.toml
  conf/experimental/test/nemo_run_nemotron_15b_fp8_256_node.toml
  conf/experimental/test/nemo_run_nemotron_15b_fp8_2_node.toml
  conf/experimental/test/nemo_run_nemotron_15b_fp8_32_node.toml
  conf/experimental/test/nemo_run_nemotron_15b_fp8_4_node.toml
  conf/experimental/test/nemo_run_nemotron_15b_fp8_64_node.toml
  conf/experimental/test/nemo_run_nemotron_15b_fp8_8_node.toml
  conf/experimental/test_scenario/nemo_run_nemotron15b_bf16.toml
  conf/experimental/test_scenario/nemo_run_nemotron15b_fp8.toml
Labels: enhancement

#384 Fix megatron ref sbatch
  tests/ref_data/megatron-run.sbatch
Labels: bug
