Repository NVIDIA/cloudai, pull requests merged in 2025-03, with the labels that each got.

#381 Refactor Callbacks on CloudAI Nemo Run Script
  src/cloudai/workloads/nemo_run/cloudai_nemorun.py
Labels: enhancement

#389 Converged Configs for Nemotron15b 2-64 nodes for Nemo2.0
  conf/experimental/test/nemo_run_nemotron_15b_bf16_128_node.toml
  conf/experimental/test/nemo_run_nemotron_15b_bf16_16_node.toml
  conf/experimental/test/nemo_run_nemotron_15b_bf16_256_node.toml
  conf/experimental/test/nemo_run_nemotron_15b_bf16_2_node.toml
  conf/experimental/test/nemo_run_nemotron_15b_bf16_32_node.toml
  conf/experimental/test/nemo_run_nemotron_15b_bf16_4_node.toml
  conf/experimental/test/nemo_run_nemotron_15b_bf16_64_node.toml
  conf/experimental/test/nemo_run_nemotron_15b_bf16_8_node.toml
  conf/experimental/test/nemo_run_nemotron_15b_fp8_16_node.toml
  conf/experimental/test/nemo_run_nemotron_15b_fp8_2_node.toml
  conf/experimental/test/nemo_run_nemotron_15b_fp8_32_node.toml
  conf/experimental/test/nemo_run_nemotron_15b_fp8_4_node.toml
  conf/experimental/test/nemo_run_nemotron_15b_fp8_64_node.toml
  conf/experimental/test/nemo_run_nemotron_15b_fp8_8_node.toml
  conf/experimental/test_scenario/nemo_run_nemotron15b_bf16.toml
  conf/experimental/test_scenario/nemo_run_nemotron15b_fp8.toml
Labels: enhancement

#388 Update NeMo docker image to nvcr.io/nvidia/nemo:24.12.01
  src/cloudai/workloads/nemo_launcher/nemo_launcher.py
  tests/ref_data/nemo-launcher.sbatch
Labels: enhancement

#391 Refactor NeMoLauncher report generation to report avg, min, max, and median
  src/cloudai/workloads/nemo_launcher/report_generation_strategy.py
  tests/report_generation_strategy/test_nemo_launcher_report_generation_strategy.py
Labels: enhancement

#392 More logs and tests for uninstall logic
  src/cloudai/installer/slurm_installer.py
  tests/test_slurm_installer.py
Labels: enhancement

#390 Ensure unique NeMo Launcher job names using timestamp to avoid conflicts
  src/cloudai/workloads/nemo_launcher/slurm_command_gen_strategy.py
  tests/ref_data/nemo-launcher.sbatch
  tests/slurm_command_gen_strategy/test_nemo_launcher_slurm_command_gen_strategy.py
  tests/test_acceptance.py
Labels: enhancement

#383 Modifications for adding more agents (other than Shmoo).
  src/cloudai/__init__.py
  src/cloudai/_core/configurator/base_agent.py
  src/cloudai/_core/configurator/cloudai_gym.py
  src/cloudai/_core/configurator/grid_search.py
  src/cloudai/_core/registry.py
  src/cloudai/_core/test.py
  src/cloudai/cli/handlers.py
  tests/test_registry.py
Labels: enhancement

#395 Close the loop on policy update for smarter agents
  src/cloudai/cli/handlers.py
Labels: enhancement

#386 Prepare for using multiple reporters per test definition
  pyproject.toml
  src/cloudai/__init__.py
  src/cloudai/_core/registry.py
  src/cloudai/_core/reporter.py
  src/cloudai/_core/test_parser.py
  src/cloudai/_core/test_scenario.py
  src/cloudai/_core/test_scenario_parser.py
  src/cloudai/_core/test_template.py
  tests/test_init.py
  tests/test_registry.py
  tests/test_test_scenario.py
Labels: enhancement, feature

#394 Allow skipping cache validation
  USER_GUIDE.md
  src/cloudai/_core/base_installer.py
  src/cloudai/cli/cli.py
  src/cloudai/cli/handlers.py
  src/cloudai/installer/slurm_installer.py
  src/cloudai/installer/standalone_installer.py
  tests/test_acceptance.py
  tests/test_base_installer.py
  tests/test_cli.py
  tests/test_slurm_installer.py
  tests/test_standalone_installer.py
Labels: enhancement, feature

#403 Refactor NcclTestReportGenerationStrategy
  src/cloudai/workloads/nccl_test/performance_report_generator.py
  src/cloudai/workloads/nccl_test/report_generation_strategy.py
  tests/report_generation_strategy/test_nccl_report_generation_strategy.py
Labels: enhancement

#406 Fix copyright years
  conf/common/system/example_slurm_cluster.toml
  src/cloudai/installer/standalone_installer.py
  tests/test_job_submission_error.py
  tests/test_parser.py
  tests/test_standalone_installer.py
Labels: bug, documentation

#405 Fix typo in the name/description field for a test
  conf/experimental/test/nemo_run_nemotron_15b_fp8_256_node.toml
Labels: documentation

#404 Support installing PythonExecutable in a subpath
  src/cloudai/_core/installables.py
  src/cloudai/installer/slurm_installer.py
  tests/test_slurm_installer.py
Labels: enhancement

#400 Generate scenario-level report
  pyproject.toml
  requirements.txt
  src/cloudai/_core/base_runner.py
  src/cloudai/_core/reporter.py
  src/cloudai/_core/runner.py
  src/cloudai/util/general-report.jinja2
Labels: feature

#407 Add Prediction Report to NCCL tests
  src/cloudai/__init__.py
  src/cloudai/_core/test.py
  src/cloudai/_core/test_scenario_parser.py
  src/cloudai/workloads/nccl_test/__init__.py
  src/cloudai/workloads/nccl_test/nccl.py
  src/cloudai/workloads/nccl_test/performance_report_generation_strategy.py
  src/cloudai/workloads/nccl_test/prediction_report_generation_strategy.py
  src/cloudai/workloads/nccl_test/prediction_report_generator.py
  tests/report_generation_strategy/test_nccl_prediction_report_generator.py
  tests/report_generation_strategy/test_nccl_report_generation_strategy.py
  tests/test_test_scenario.py
Labels: feature

#414 Migrate NCCL performance data parsing to performance report generator
  src/cloudai/workloads/nccl_test/performance_report_generator.py
  src/cloudai/workloads/nccl_test/prediction_report_generator.py
  tests/report_generation_strategy/test_nccl_prediction_report_generator.py
  tests/report_generation_strategy/test_nccl_report_generation_strategy.py
Labels: bug, enhancement

#417 Use abs path to jinja2 template
  src/cloudai/_core/reporter.py
Labels: bug

#416 Support 'unknown' cmd args in NCCL cmd generation
  src/cloudai/workloads/nccl_test/slurm_command_gen_strategy.py
  tests/slurm_command_gen_strategy/test_nccl_slurm_command_gen_strategy.py
Labels: enhancement

#418 New Constraint Check Nemo2.0
  src/cloudai/workloads/nemo_run/nemo_run.py
Labels: enhancement

#412 Reporting for encoded logs
  src/cloudai/_core/reporter.py
  src/cloudai/workloads/nemo_run/report_generation_strategy.py
  tests/report_generation_strategy/test_nemo_run_report_generation_strategy.py
Labels: bug, enhancement

#420 Fix system serialization
  src/cloudai/systems/slurm/slurm_system.py
  tests/test_slurm_system.py
Labels: bug

#425 Make is_dse_job a property of TestDefinition
  src/cloudai/_core/test.py
  src/cloudai/cli/handlers.py
  tests/test_job_type_handler.py
Labels: enhancement

#429 Consider only RUNNING state as running job
  src/cloudai/systems/slurm/slurm_system.py
  tests/test_slurm_system.py
Labels: bug

#430 Nemo2.0 Lora + Null tokenizer
  conf/common/test/nemo_run_llama3_8b_lora.toml
  conf/common/test_scenario/nemo_run_llama3_8b_lora.toml
  src/cloudai/systems/slurm/strategy/slurm_command_gen_strategy.py
  src/cloudai/workloads/nemo_run/cloudai_nemorun.py
  src/cloudai/workloads/nemo_run/nemo_run.py
  src/cloudai/workloads/nemo_run/slurm_command_gen_strategy.py
  tests/ref_data/gpt-no-hook.sbatch
  tests/ref_data/gpt-pre-test.sbatch
  tests/ref_data/grok-no-hook.sbatch
  tests/ref_data/grok-pre-test.sbatch
  tests/ref_data/megatron-run.sbatch
  tests/ref_data/nccl.sbatch
  tests/ref_data/nemo-run-no-hook.sbatch
  tests/ref_data/nemo-run-pre-test.sbatch
  tests/ref_data/sleep.sbatch
  tests/ref_data/slurm_container.sbatch
  tests/ref_data/ucc.sbatch
  tests/slurm_command_gen_strategy/test_common_slurm_command_gen_strategy.py
  tests/slurm_command_gen_strategy/test_nemo_run_slurm_command_gen_strategy.py
  tests/slurm_command_gen_strategy/test_slurm_container_slurm_command_gen_strategy.py
Labels: enhancement

#435 Update USER_GUIDE.md
  USER_GUIDE.md
Labels: documentation
