Repository NVIDIA/cloudai, pull requests merged in 2025-01, with the labels that each got.

#317 Fix ABC usage issues
  src/cloudai/_core/command_gen_strategy.py
  src/cloudai/_core/json_gen_strategy.py
  src/cloudai/_core/test.py
Labels: enhancement

#322 Add test hooks to USER_GUIDE.md
  USER_GUIDE.md
Labels: documentation

#323 Do not require enroot on head node
  src/cloudai/_core/base_installer.py
  src/cloudai/installer/slurm_installer.py
  src/cloudai/util/docker_image_cache_manager.py
  tests/test_docker_image_cache_manager.py
Labels: bug

#321 Parser for DSE
  src/cloudai/_core/test.py
  src/cloudai/_core/test_parser.py
  src/cloudai/_core/test_template_strategy.py
  src/cloudai/schema/test_template/chakra_replay/slurm_command_gen_strategy.py
  src/cloudai/schema/test_template/nccl_test/kubernetes_json_gen_strategy.py
  src/cloudai/schema/test_template/nccl_test/slurm_command_gen_strategy.py
  src/cloudai/schema/test_template/nemo_launcher/slurm_command_gen_strategy.py
  src/cloudai/schema/test_template/nemo_run/slurm_command_gen_strategy.py
  src/cloudai/schema/test_template/sleep/kubernetes_json_gen_strategy.py
  src/cloudai/schema/test_template/sleep/slurm_command_gen_strategy.py
  src/cloudai/schema/test_template/slurm_container/slurm_command_gen_strategy.py
  src/cloudai/schema/test_template/ucc_test/slurm_command_gen_strategy.py
  src/cloudai/systems/slurm/strategy/slurm_command_gen_strategy.py
  src/cloudai/test_definitions/gpt.py
  src/cloudai/test_definitions/grok.py
  src/cloudai/test_definitions/jax_toolbox.py
  src/cloudai/test_definitions/nemotron.py
  tests/slurm_command_gen_strategy/test_chakra_replay_slurm_command_gen_strategy.py
  tests/slurm_command_gen_strategy/test_common_slurm_command_gen_strategy.py
  tests/slurm_command_gen_strategy/test_nccl_slurm_command_gen_strategy.py
  tests/slurm_command_gen_strategy/test_sleep_slurm_command_gen_strategy.py
  tests/slurm_command_gen_strategy/test_ucc_slurm_command_gen_strategy.py
Labels: feature

#328 Remove conf/common/test/chakra_replay.toml
  conf/common/test/chakra_replay.toml
  conf/common/test_scenario/chakra_replay.toml
Labels: bug

#330 Extend tests for job status checking
  tests/test_slurm_system.py
Labels: enhancement, unit-tests

#331 Add container_mounts to final_cmd_args for NCCL_TOPO_FILE
  src/cloudai/schema/test_template/nemo_launcher/slurm_command_gen_strategy.py
  tests/slurm_command_gen_strategy/test_nemo_launcher_slurm_command_gen_strategy.py
Labels: bug

#336 Fixed typo in NeMoRunTestDefinition docstr
  src/cloudai/test_definitions/nemo_run.py
Labels: documentation

#337 Mount NCCL_TOPO_FILE in NCCL test
  src/cloudai/schema/test_template/nccl_test/slurm_command_gen_strategy.py
  tests/slurm_command_gen_strategy/test_nccl_slurm_command_gen_strategy.py
Labels: bug

#339 Replace NCCL_TEST_SPLIT_MASK with NCCL_TESTS_SPLIT_MASK
  conf/common/test/nccl_test_all_gather.toml
  conf/common/test/nccl_test_reduce_scatter.toml
  conf/hook/test/nccl_test_all_gather.toml
Labels: bug

#327 Configurable CloudAIGym from TestRun
  conf/common/test/dse_jaxtoolbox_grok.toml
  conf/common/test_scenario/dse_jaxtoolbox.toml
  pyproject.toml
  requirements.txt
  src/cloudai/_core/configurator/cloudai_gym.py
  src/cloudai/test_definitions/jax_toolbox.py
  tests/test_cloudaigym.py
Labels: feature

#338 Check RW permissions for install and results folders
  .github/workflows/ci.yml
  pyproject.toml
  src/cloudai/_core/base_installer.py
  src/cloudai/cli/handlers.py
  src/cloudai/util/__init__.py
  tests/test_base_installer.py
Labels: bug

#329 Configurable agents interface
  src/cloudai/_core/configurator/base_agent.py
  src/cloudai/_core/configurator/grid_search.py
  tests/test_agents.py
Labels: feature

#340 Bug fix in job completion checks
  src/cloudai/report_generator/report_generator.py
  src/cloudai/systems/slurm/slurm_system.py
  tests/test_slurm_system.py
Labels: bug

#335 retry docker image enroot when cluster requires specifying GPU resource
  src/cloudai/util/docker_image_cache_manager.py
  tests/test_docker_image_cache_manager.py
Labels: bug

#342 Unified handling for install and output folders
  .github/workflows/ci.yml
  src/cloudai/_core/base_installer.py
  src/cloudai/cli/handlers.py
  src/cloudai/util/__init__.py
  tests/test_base_installer.py
Labels: bug, enhancement

#345 Fix time limit calculation to include pre and post test hook durations
  src/cloudai/_core/test_scenario_parser.py
  tests/test_test_scenario.py
Labels: bug

#347 Reflect Andrei's comments for PR345
  src/cloudai/_core/test_scenario_parser.py
  tests/test_test_scenario.py
Labels: enhancement

#346 fix the docker url for dse [for QA]
  conf/common/test/dse_jaxtoolbox_grok.toml
Labels: bug

#344 Docs Review - Suggested Changes
  README.md
  USER_GUIDE.md
  doc/DEV.md
Labels: documentation

#343 Step integration with Runner
  src/cloudai/_core/configurator/cloudai_gym.py
  src/cloudai/cli/handlers.py
  tests/conftest.py
  tests/test_cloudaigym.py
Labels: feature

#348 Integrate report generation into Gym
  conf/common/test/dse_jaxtoolbox_grok.toml
  conf/common/test_scenario/dse_jaxtoolbox.toml
  src/cloudai/_core/base_runner.py
  src/cloudai/_core/configurator/cloudai_gym.py
  src/cloudai/report_generator/report_generator.py
  tests/test_cloudaigym.py
Labels: feature

#349 Move conf/staging/nemo/ to CloudAI
  conf/release/nemo_acceptance/test/gpt3_126m_mock.toml
  conf/release/nemo_acceptance/test/gpt3_126m_pile.toml
  conf/release/nemo_acceptance/test/nccl_test_all_reduce_loopback.toml
  conf/release/nemo_acceptance/test_scenario/gpt3_126m_mock.toml
  conf/release/nemo_acceptance/test_scenario/gpt3_126m_pile.toml
  conf/release/nemo_acceptance/test_scenario/nccl_test_loopback.toml
Labels: enhancement
